# Vendor meta-ctopai layer
# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# Empty pattern - this vendor layer only provides shared infrastructure
# Board-specific layers are nested under it (e.g. meta-ceb-gnrd).
BBFILE_COLLECTIONS += "meta-ctopai"
BBFILE_PATTERN_meta-ctopai = ""
BBFILE_PATTERN_IGNORE_EMPTY_meta-ctopai = "1"
LAYERSERIES_COMPAT_meta-ctopai = "wrynose whinlatter"
