export const rows = `
introduction|OpenBMC 与带外管理|BMC 是服务器上的独立管理控制器。主机操作系统失去响应时，只要管理控制器仍有供电和网络，管理员就能继续检查设备。~OpenBMC 为 BMC 提供 Linux 系统及管理服务。Yocto 构建镜像，systemd 管理服务，D-Bus 连接进程，Redfish 和 IPMI 提供外部接口。~学习时区分 Host、Chassis 和 BMC。重启管理控制器与重启主机影响不同，电源状态也不能混用。|管理网络~服务进程~物理设备|观察管理接口与主机接口的连接方式，标记独立供电、串口和控制信号。~在模拟器中访问管理接口，再查看 BMC 与 Host 的状态对象。~用同一份记录描述操作对象、请求状态和观察到的实际状态。|能解释管理请求最终经过哪些软件层，以及模拟器不能证明哪些硬件行为。~若接口可访问而主机操作无效，先检查平台是否实现了对应控制链路。|busctl list\nsystemctl --failed\ncat /etc/os-release
environment-setup|开发环境与构建隔离|完整镜像构建需要 Linux 环境、足够的内存和较大的磁盘空间。Windows 目录可以阅读源码，正式构建应放在合适的 Linux 文件系统。~原教程介绍原生 Linux、容器与 SDK。容器固定宿主依赖，SDK 用于单个应用交叉编译，首次生成 SDK 仍需要完整构建。~下载缓存与 sstate 缓存用途不同。团队应记录源码版本、容器版本和 machine，避免只记录一次成功的命令。|Linux 主机~构建容器~目标镜像|检查 CPU、内存、磁盘与 locale，确认构建目录可写。~选择原生 Linux 或容器，并按照源教程安装该发行版对应依赖。~初始化构建环境后保存配置和版本信息，先做一次小范围构建。|能够重复进入同一构建环境，且缓存目录在容器退出后仍然存在。~内存耗尽时降低并行度，磁盘不足时先定位下载、工作目录和缓存占用。|uname -a\nfree -h\ndf -h\nlocale\ngit rev-parse HEAD
first-build|首次构建与 QEMU 启动|machine 决定设备树、内核配置和平台服务。初始化环境前先确认目标名称，再构建 obmc-phosphor-image。~第一次构建包含源代码下载和大量宿主工具编译。一次网络错误不代表配方本身错误，应从失败任务的日志判断原因。~启动 QEMU 时，镜像、模拟机型和网络转发需要匹配。能够登录 BMC 只说明软件启动成功，不能代替真板电源或风扇验证。|配置 machine~构建镜像~启动模拟器|按原教程的 setup 命令选择 QEMU 对应 machine，在初始化后的 shell 内运行构建。~从 tmp/deploy/images 下确认镜像名、大小和生成时间。~用匹配的 QEMU machine 启动，记录串口启动日志并查询 Redfish 服务根。|串口出现登录提示，管理接口可访问，核心服务没有持续崩溃。~无法连接时依次检查进程、端口转发、监听端口、登录凭证与服务日志。|bitbake obmc-phosphor-image\nbitbake -e obmc-phosphor-image\nqemu-system-arm -machine help
development-workflow|配方、补丁与增量开发|应用代码、BitBake 配方和平台配置属于不同修改位置。应用行为变化应修改源代码，平台差异通常通过自有 layer 和 bbappend 表达。~devtool 将配方源码放入开发工作区，适合反复编辑和增量构建。finish 将修改整理到指定 layer，执行前应检查补丁和工作区状态。~sstate 复用已完成任务的结果。缓存是否命中取决于任务输入与签名，不能用缓存目录大小判断效果。|源代码~配方元数据~平台 layer|选择一个小型服务，记录原始 SRCREV 与当前配方。~使用 devtool modify 和 devtool build 修改、构建，再在测试目标验证。~审查补丁内容和 bbappend 路径，确认干净构建仍能获得相同行为。|补丁在工作区之外也能复现，配方命名与匹配规则正确。~更改没有生效时检查实际 SRCREV、配方覆盖、workspace 和构建任务日志。|devtool status\nbitbake-layers show-layers\nbitbake-layers show-appends
building-qemu|QEMU 版本与机型支持|系统提供的 QEMU 不一定包含所需 ASPEED machine。先检查版本和 machine 列表，缺失时再选用构建系统提供的 QEMU 或源码构建。~模拟 CPU 架构与镜像必须兼容。AST2500、AST2600 等机型名称及支持范围取决于 QEMU 版本。~模拟器适合验证服务、接口与部分驱动路径。模拟的器件数量、时序和错误行为与实板可能不同。|QEMU 可执行文件~machine 模型~Flash 镜像|找出当前实际执行的 QEMU 路径，记录其版本。~查询可用 machine 列表并与源教程启动参数逐项对照。~保存一份启动脚本，明确镜像路径、串口输出和网络转发。|重启实验时可以复现同一模拟环境，且启动脚本没有隐式依赖当前目录。~Machine type not found 时检查调用到的二进制，避免误用另一版本。|which qemu-system-arm\nqemu-system-arm --version\nqemu-system-arm -machine help
devtool-workflow-guide|devtool 部署与调试闭环|开发闭环包含提取源码、修改、构建、部署、重启服务和验证。构建成功只代表产物生成，目标系统仍可能运行旧文件。~部署前确认目标架构、动态库依赖与服务名。临时部署适合测试，最终应通过配方生成镜像。~gdbserver 与交叉 GDB 需要匹配的符号和源码。调试日志、二进制和源码版本应成套保存。|workspace~目标服务~调试符号|在模拟器上选择可恢复的服务，先保存原文件与服务状态。~修改一条可观察行为并增量构建，部署后确认文件时间与实际进程。~对目标设置断点或读取日志，记录验证结果后将修改整理为补丁。|服务表现与代码修改一致，镜像重新构建后仍然保持该行为。~服务启动失败时检查 ELF 架构、共享库、D-Bus 名称冲突与 systemd 日志。|devtool status\nfile ./service-binary\nsystemctl status phosphor-state-manager*\njournalctl -b --no-pager -n 50
gerrit-contribution-guide|Gerrit 评审与提交身份|OpenBMC 的贡献流程将代码评审、提交身份和 CI 结果关联起来。提交消息应说明问题、行为变化和验证方式。~Change-Id 用于关联同一评审的不同 patch set。修订已有评审时保留该标识，避免形成互不关联的新评审。~内核改动需要结合上游贡献流程和项目政策。记录上游链接及适用版本，有助于减少长期本地补丁维护。|Git 提交~Gerrit patch set~CI 结果|核对 Git 身份与 Gerrit 账户的登记邮箱。~在本地检查提交消息中的 Sign-off 与 Change-Id，按教程配置 commit-msg hook。~阅读评审和 CI 日志，对失败进行本地复现后再更新提交。|提交说明能让未参与讨论的评审者理解修改原因和验证范围。~缺少 Change-Id 时检查 hook，身份不匹配时检查 committer 邮箱。|git config user.name\ngit config user.email\ngit log -1 --format=fuller\ngit status --short
openbmc-overview|OpenBMC 软件分层|外部请求通常进入 bmcweb 或 IPMI 服务，再读取或修改 D-Bus 对象。底层服务通过 Linux 驱动访问硬件。~meta-phosphor 提供通用能力，SoC layer 提供芯片支持，平台 layer 保存板级差异。层次关系决定了修改放在哪里。~故障定位应沿数据路径逐层检查。网页没有温度读数时，先确认 API、D-Bus、hwmon 和驱动各层的实际输出。|外部接口~D-Bus 服务~内核驱动|从当前仓库列出通用、SoC 与平台 layer，并查找一个目标配方。~选择一个管理对象，记录其 Redfish 路径、D-Bus 接口及后端服务。~找到该服务的启动单元与日志，画出实际调用关系。|能够从一个用户可见功能追踪到服务和硬件依赖。~不要根据目录名推断配方最终来源，使用 bitbake-layers 与 bitbake -e 确认。|bitbake-layers show-layers\nbitbake-layers show-recipes\nbusctl list\nsystemctl --failed
d-bus-guide|D-Bus 对象模型与 Object Mapper|一个 D-Bus 对象由服务名、对象路径和接口描述。属性表达当前数据，方法表达操作，信号表达异步变化。~OpenBMC 的服务归属可能随对象和实现变化。Object Mapper 按对象路径与接口查询拥有者，客户端应避免写死所有服务名。~类型签名约束参数与返回值。busctl 调用失败时应先 introspect，再核对接口、成员和签名。|服务名~对象路径~接口与成员|使用 busctl list 找到运行服务，再用 tree 查看对象路径。~选择一个对象进行 introspect，读取属性并解释类型签名。~监视一次实际变化，比较调用结果与 PropertiesChanged 信号。|能区分对象不存在、接口不存在、属性类型错误与权限失败。~UnknownObject 时查 Mapper 和对象生命周期，AccessDenied 时检查总线策略与调用身份。|busctl list\nbusctl tree xyz.openbmc_project.ObjectMapper\nbusctl introspect xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper
state-manager-guide|BMC、机箱与主机状态|BMCState、ChassisState 与 HostState 描述不同对象。RequestedTransition 表达请求，CurrentState 表达实际结果，二者存在时间差。~电源控制由状态服务、systemd target 和板级 GPIO 配合完成。服务接受请求后仍需要实际电源反馈证明操作完成。~恢复策略、启动进度与 watchdog 会影响自动行为。分析重启应把请求、状态迁移和触发来源放在同一时间线上。|状态请求~systemd target~硬件反馈|查看 BMC、Chassis 和 Host 的状态对象，记录路径和属性值。~在测试平台发起一次受控转换，同时采集状态与服务日志。~检查转换失败或超时后的状态，确认恢复策略没有隐藏真实故障。|请求后的实际状态与硬件反馈一致，日志能说明转换过程。~卡在 Quiesced 时结合故障日志、目标依赖和恢复策略定位，避免反复重启掩盖原因。|obmcutil state\nbusctl tree xyz.openbmc_project.State.Host\nsystemctl list-units 'obmc*'\njournalctl -b -n 60 --no-pager
custom-d-bus-services-guide|自定义 D-Bus 服务|服务开发从接口契约开始。YAML 定义属性、方法与错误，sdbusplus 生成绑定，应用实现处理逻辑。~同步服务和基于 Boost.Asio 的异步服务适合不同负载。回调中阻塞会拖慢事件处理，异步对象的生命周期需要明确。~服务还需要 systemd 单元、D-Bus 策略与 Yocto 配方。二进制成功编译后仍要确认服务名和接口真正可见。|接口 YAML~服务实现~打包与启动|参考原教程的 Greeter 示例，先定义一个只读属性和一个简单方法。~编译部署到 QEMU，并检查服务启动、名称注册和对象发布。~通过 busctl 验证属性与方法，再重启服务观察对象恢复。|接口行为与 YAML 契约一致，错误输入得到可解释的错误返回。~Name already taken 时查重复实例，属性不可见时查对象发布和接口注册顺序。|busctl list\nsystemctl --failed\njournalctl -b -u phosphor-greeter --no-pager
systemd-boot-ordering-guide|systemd 依赖与启动顺序|Wants 和 Requires 决定依赖拉起及失败关系。After 和 Before 决定顺序，单独设置 After 不会自动启动另一服务。~进程启动与服务就绪存在区别。客户端可能需要等待 D-Bus 名称或对象出现，不能只依赖某个进程已经运行。~模板单元通过实例参数服务多个 Host。oneshot 的执行结果和 RemainAfterExit 会影响后续状态观察。|依赖关系~执行顺序~就绪条件|选择一个服务，查看 Unit 中的 Wants、Requires、After 与 Before。~用 critical-chain 找到启动关键路径，再与该服务日志对照。~检查一个模板实例，确认实例编号与 Host 编号一致。|能够解释服务为何启动、何时启动，以及失败如何影响依赖者。~服务未拉起时查依赖链接，过早访问对象时查就绪条件和客户端重试。|systemctl cat phosphor-mapper.service\nsystemd-analyze critical-chain\nsystemd-analyze blame\nsystemctl list-dependencies
d-bus-sensors-guide|传感器数据发布与阈值|dbus-sensors 的多个 daemon 处理不同器件类型。配置匹配后，服务读取硬件数据并创建传感器对象。~Sensor.Value、单位、量程和阈值共同描述读数。数值正确但单位或缩放错误，同样会造成管理接口误判。~告警触发与恢复通常需要考虑滞回和电源状态。断电期间的无效读数不应直接当作真实过温。|硬件采样~传感器对象~阈值事件|从 hwmon 或设备接口确认一项原始读数，再找到对应 D-Bus 对象。~核对单位、缩放、量程与阈值配置，再查询外部接口。~在可控测试输入下观察告警触发和恢复，记录滞回区间。|内核、D-Bus 和管理接口读数一致，告警行为符合设定。~传感器缺失时检查 Probe、Type、daemon 是否打包及电源状态过滤。|ls /sys/class/hwmon\nbusctl tree xyz.openbmc_project.HwmonTempSensor\nsystemctl list-units '*sensor*'
hwmon-sensors-guide|Linux hwmon 与温度单位|hwmon 将驱动数据暴露到 sysfs。温度、风扇和电压的属性名与单位由 Linux hwmon ABI 定义。~hwmon 目录编号可能随探测顺序变化。通过 name 和实际设备路径确认器件，不能长期依赖 hwmon0 代表某个固定传感器。~phosphor-hwmon 和 dbus-sensors 的配置方式不同。迁移时应核对服务、对象名、阈值与配置来源。|芯片驱动~hwmon 属性~OpenBMC 传感器服务|列出所有 hwmon name，将每个目录关联到实际总线器件。~读取一个 temp*_input，并按该属性的 ABI 单位换算。~比较 D-Bus 发布值和 hwmon 值，解释正常采样时间差。|能把一个外部读数追踪到具体 sysfs 文件和驱动。~数值差一千倍时检查毫度与摄氏度转换，设备缺失时查驱动绑定。|grep . /sys/class/hwmon/hwmon*/name\nfind /sys/class/hwmon -name 'temp*_input'\ndmesg | tail -n 40
entity-manager-guide|Entity Manager 硬件发现|Entity Manager 根据 Probe 匹配硬件记录，并把 Exposes 配置发布到 D-Bus。它提供硬件描述，传感器 daemon 负责实际采样。~JSON 的语法正确只证明文件可解析。Probe 条件、接口类型、总线和地址仍需与真实硬件及当前实现匹配。~FRU 信息可驱动动态配置。热插拔和重载需要同时观察发现记录、配置对象以及消费配置的服务。|Probe 匹配~Exposes 发布~配置消费|选择一个已有平台 JSON，解释 Name、Probe 与 Exposes 的作用。~在测试目标确认 Probe 所引用的 D-Bus 信息真实存在。~观察 Entity Manager 日志，再确认传感器 daemon 是否创建对应对象。|配置对象与实际设备一致，传感器服务能消费该配置。~Probe 不匹配时先检查原始 FRU 或发现属性，避免直接改成无条件匹配掩盖问题。|journalctl -b -u entity-manager --no-pager\nbusctl tree xyz.openbmc_project.EntityManager\nls /usr/share/entity-manager/configurations
fan-control-guide|风扇区域与闭环控制|风扇控制把温度输入、控制策略与 PWM 输出组织为 zone。一个 zone 可以包含多个温度来源和多个风扇。~手动 PWM 只适合受控测试。自动控制需要有效输入、合理下限和失效保护，以覆盖传感器失联或风扇异常。~PID 参数与 stepwise 策略影响噪声、温度和响应速度。调参前先记录基线，不要仅凭静态温度判断稳定性。|温度输入~控制 zone~PWM 与转速反馈|核对温度、风扇转速和 PWM 对象是否属于同一散热区域。~在测试平台记录自动模式下温度、输出和转速的变化。~验证无效输入后的 failsafe，测试结束后确认自动模式恢复。|负载变化时温度与风扇输出响应合理，失联时进入定义的保护状态。~满速运行时检查输入有效性与 failsafe，振荡时检查增益、采样周期和速率限制。|systemctl status phosphor-pid-control\njournalctl -b -u phosphor-pid-control --no-pager\nls /sys/class/hwmon
power-management-guide|电源时序与 PSU 反馈|开机涉及请求、使能信号、供电轨与 Power Good。状态服务需要根据实际反馈判断是否成功。~PSU 监控与电压调节器管理承担不同任务。平台配置需要匹配 PMBus 器件、寄存器定义和电源拓扑。~功率限制、冗余策略和掉电恢复策略会影响整机行为。观察异常应包含负载、电源状态和策略设置。|开机请求~电源控制~Power Good|整理原理图中的电源使能、Power Good 与 PSU presence 信号。~从日志观察一次受控开机，按时间记录各级状态。~检查 PSU 告警、冗余变化与恢复策略，确认故障路径可观测。|开机完成条件来自实际反馈，PSU 故障能产生可追踪事件。~电源启动失败时检查 GPIO 极性、时序和 PSU 状态，而非只查看 HostState。|obmcutil state\nsystemctl list-units '*power*'\njournalctl -b --no-pager -n 80\ncat /proc/interrupts
user-manager-guide|用户、角色与账号策略|phosphor-user-manager 管理本地用户及权限映射。Redfish 角色、D-Bus 权限和 IPMI 通道权限需要一致检查。~账号锁定和密码策略影响登录流程。身份认证成功与操作授权成功是两个独立检查点。~会话、LDAP 与 MFA 等能力取决于版本和平台配置。不要把教程中的可选功能视为所有镜像默认提供。|认证身份~角色权限~管理会话|用测试账号查询其角色与通道权限，记录可访问接口。~分别验证只读用户和管理员的预期操作权限。~观察账号锁定、会话退出和策略持久化行为。|低权限账号只能执行允许操作，策略变更与日志一致。~认证通过但操作失败时查权限映射，所有登录失败时检查账号状态与 PAM 日志。|busctl tree xyz.openbmc_project.User.Manager\nsystemctl status phosphor-user-manager\njournalctl -b --no-pager -n 60
network-guide|管理网络、DHCP 与 NCSI|phosphor-network 管理网络配置并与 systemd-networkd 等组件协作。IP 地址、路由和 DNS 分别影响不同连接阶段。~专用管理网口和 NCSI 共享网络路径有不同硬件依赖。链路 up 并不保证地址、路由和上游交换机配置正确。~静态 IP、VLAN 或 MAC 修改可能中断当前管理连接。实验前保留串口访问，并记录原始配置。|链路~地址与路由~管理服务|通过串口记录接口、地址、路由和 DNS。~在测试网络验证 DHCP 或静态配置，再测试本地与跨网段访问。~重启后确认配置持久化，NCSI 平台同时检查 channel 与 package 状态。|地址与路由符合预期，管理服务在配置完成后可访问。~按链路、地址、路由、DNS、监听端口顺序定位，避免把所有失败归为网络服务问题。|ip link\nip address\nip route\nnetworkctl status\nresolvectl status
led-manager-guide|LED 物理驱动与逻辑组|物理 LED 由 GPIO 或其他驱动控制，逻辑 LED group 表达定位、故障和电源等管理含义。~组优先级决定多个状态同时要求同一灯时的结果。验证单个 LED 亮灭不足以证明组合策略正确。~JSON 运行配置与 YAML 编译配置可能并存。实际使用哪种方式取决于当前配方和服务实现。|逻辑状态~LED group~物理 LED|建立逻辑组与物理灯的映射表，核对极性和默认状态。~检查定位组及故障组的配置，观察组合状态的优先级。~重启后验证默认状态和策略恢复，再检查外部接口表达。|实际灯光状态符合逻辑组与优先级，重启后没有异常闪烁。~D-Bus 正常而灯不变化时查 sysfs、GPIO 与驱动，组未生效时查配置格式和路径。|ls /sys/class/leds\nbusctl tree xyz.openbmc_project.LED.GroupManager\nsystemctl list-units '*led*'
certificate-manager-guide|证书链、CSR 与服务重载|HTTPS 证书需要与私钥配对，证书链需要连接到客户端信任的根。自签名证书适合隔离实验，部署环境应使用合适的信任体系。~证书中的主机名和有效期会影响客户端验证。系统时间错误也会造成证书未生效或过期。~替换证书后需要确认服务实际加载了新证书。文件更新成功不等于客户端已经看到新身份。|私钥与 CSR~证书链~HTTPS 服务|读取当前服务器证书的主题、SAN 和有效期。~按源教程在实验平台完成 CSR 或证书替换。~重新建立 TLS 连接，确认服务器呈现的证书指纹已变化。|客户端按预期验证证书链、名称与时间，服务恢复后仍使用新证书。~验证失败时分别检查时间、SAN、链完整性与信任根。|openssl x509 -in server.pem -noout -subject -issuer -dates\nopenssl x509 -in server.pem -noout -fingerprint -sha256\ntimedatectl
time-manager-guide|系统时钟、RTC 与 NTP|时间管理协调系统时钟、RTC、NTP 与可能的主机时间来源。多个写入方同时校时会造成跳变。~NTP 启用与已同步需要分开检查。网络、DNS 和时间服务状态都会影响同步结果。~事件日志、证书验证和故障关联依赖可靠时间。记录测试数据时应明确时区和时间源。|时间来源~系统时钟~日志时间戳|读取当前时间、时区与同步状态，并记录 RTC 状态。~检查 NTP 服务器可达性和时间服务日志。~重启后确认时间恢复来源，比较事件日志与测试机时间。|时间持续同步且事件顺序可靠，重启后的时间来源明确。~证书错误或日志乱序时先排查时钟跳变，再检查上层服务。|date -u\ntimedatectl\ntimedatectl timesync-status\nhwclock -r
inventory-manager-guide|Inventory、FRU 与关联关系|Inventory 表达设备身份、位置和存在状态。FRU 提供制造商、型号、序列号等可替换部件信息。~Association 将传感器、库存项与机箱关系连接起来。外部接口常依赖这些关系组织资源。~EEPROM 内容、D-Bus 库存对象和 Redfish 资源需要保持一致。设备不存在时应检查状态表达，而非仅删除读数。|FRU 数据~库存对象~资源关联|读取一项 FRU，并核对板卡上的型号或序列号。~在 D-Bus 中找到对应库存项，记录 Present 等属性。~检查传感器关联和外部资源归属，解释设备插拔时的变化。|库存身份、存在状态和传感器归属一致。~FRU 可读但资源缺失时查发现服务、配置 Probe 与 Association。|busctl tree xyz.openbmc_project.Inventory.Manager\nipmitool fru print\nsystemctl list-units '*fru*'
watchdog-guide|Watchdog 超时与恢复动作|Watchdog 通过定期刷新证明受监控方仍在正常运行。计时器配置包含超时、启用状态和到期动作。~主机 watchdog 与 BMC 自身 watchdog 的对象和影响不同。测试前确认究竟会重置哪一部分。~到期动作需要结合电源状态服务与平台能力验证。定时器到期但没有动作时，检查完整恢复链路。|启用计时器~定期刷新~超时动作|在可恢复实验平台记录 watchdog 当前参数与监控对象。~按教程观察刷新后的剩余时间或日志，不先改变生产策略。~设计短时故障测试并验证到期动作，测试后恢复原参数。|计时器、日志与实际恢复动作一致，正常刷新不会触发误重启。~频繁重启时核对刷新来源、超时值、启动阶段和重复控制者。|ipmitool mc watchdog get\nsystemctl list-units '*watchdog*'\njournalctl -b --no-pager -n 60
buttons-guide|按钮事件与主机动作|按钮输入经过 GPIO 或 input 子系统，再由用户态服务解释按压和释放。事件极性与电气接线必须一致。~短按、长按和去抖策略表达不同操作意图。若硬件与服务同时处理同一信号，可能产生重复动作。~按钮触发的电源操作最终仍需状态反馈。日志应关联输入事件、目标动作与实际结果。|按钮输入~事件解释~状态操作|根据原理图核对输入引脚、上拉和有效电平。~观察一次短按和释放的事件，记录时间与目标变化。~在实验平台验证长按或去抖行为，并检查是否出现重复触发。|一次按压对应预期动作，抖动不会导致多次转换。~没有事件时查 pinmux 和 input/GPIO 路径，动作重复时查多个消费者。|gpioinfo\ncat /proc/bus/input/devices\nsystemctl list-units '*button*'
gpio-management-guide|GPIO line 名称与事件监控|GPIO line 名称能把软件配置与原理图信号对齐。不同 gpiochip 的 offset 不能混作统一编号。~phosphor-multi-gpio-monitor 将边沿事件映射到 systemd target。持续监控和一次性监控适合不同场景。~GPIO 输出的逻辑值、active-low 和物理电平有区别。修改前应确认信号方向和占用者。|line 名称~边沿事件~目标单元|通过 gpioinfo 找到目标信号，核对 chip、offset 和消费者。~阅读 JSON 监控配置，确认 LineName、事件类型与目标实例。~在可控输入下观察边沿和日志，再验证重复事件行为。|软件名称对应正确引脚，事件与 target 触发一致。~Line busy 时查消费者，首次有效后失效时检查 OneShot 等配置。|gpioinfo\nsystemctl list-units '*gpio*'\njournalctl -b --no-pager -n 60
peci-thermal-monitoring|Intel PECI 温度采集|PECI 提供与支持该接口的 CPU 通信的旁带路径。温度来源和换算方式不同于普通 I2C 温度芯片。~完整链路包含控制器、客户端驱动、hwmon 与传感器 daemon。Host 电源状态会影响可读数据。~DIMM 温度和部分 CPU 指标依赖处理器支持及固件状态。QEMU 的接口验证不能证明真板 PECI 时序正确。|PECI 控制器~CPU 客户端~温度对象|核对 PECI 接线、电源条件与 CPU 地址。~检查内核驱动及 hwmon 名称，再观察原始温度。~对照 D-Bus 与 Redfish，记录 Host 不同状态下的读数有效性。|温度来源、单位和可用状态可解释，主机断电时不产生误告警。~Ping 失败先查物理与供电，hwmon 缺失再查驱动、设备树和内核配置。|dmesg | grep -i peci\nls /sys/bus/peci/devices\ngrep . /sys/class/hwmon/hwmon*/name
i2c-device-integration|I2C 拓扑、地址与驱动绑定|I2C 设备定位需要同时确认总线与地址。mux 下的逻辑总线编号可能与原理图控制器编号不同。~设备树的 compatible 选择驱动，reg 表达地址。地址可响应只说明存在设备，不能证明驱动和寄存器格式正确。~运行时绑定适合诊断，正式平台应以设备树和配方保存配置。扫描或寄存器访问前先确认器件允许相应操作。|控制器与 mux~设备地址~内核驱动|绘制控制器、mux 通道和设备的对应关系，核对原理图。~只先列出总线和已绑定设备，确认驱动及内核日志。~按数据手册验证读数，再连接 hwmon 与 Entity Manager 配置。|目标设备绑定正确驱动，读数符合数据手册，重启后配置仍成立。~ENXIO 时查地址与供电，读数异常时查驱动、字节序和 mux 路径。|i2cdetect -l\nls /sys/bus/i2c/devices\ndmesg | grep -i i2c
psu-pmbus-management|PSU 监控与 PMBus 状态|PMBus 为电源设备提供监控与控制命令。具体支持命令、数据格式和故障位需要参考器件资料。~PSU presence、输入电源状态与输出故障表达不同事实。冗余策略需要基于实际在线且健康的电源数量。~内核 PMBus 驱动、PSU 传感器服务和 phosphor-power 各有职责，应逐层确认。|PMBus 设备~功率与状态~冗余策略|核对 PSU 型号、地址与驱动支持，记录固件版本。~检查 hwmon 原始数据和 D-Bus 对象，对照负载条件。~在实验机上观察 PSU presence 或输入变化，确认库存与故障日志一致。|读数与电源状态一致，冗余丢失产生预期事件。~缺少数据时查驱动与配置，数值异常时查 LINEAR 格式、单位和支持命令。|grep . /sys/class/hwmon/hwmon*/name\nsystemctl list-units '*psu*'\njournalctl -b --no-pager -n 80
ldap-integration|LDAP 认证与角色映射|LDAP 让管理控制器使用目录服务进行身份验证。PAM、nslcd、目录配置与本地角色映射共同决定登录结果。~LDAPS 需要正确的 CA 信任、服务名称和系统时间。连接成功后仍要检查搜索基准、绑定账号与组查询。~目录组映射到 BMC 角色后，还需验证具体接口权限。不能只以一次管理员登录成功作为验收。|目录查询~身份认证~组权限映射|在测试目录建立低权限与管理员组，记录搜索基准与组属性。~验证 TLS 连接，再检查 nslcd 和 PAM 日志。~分别登录并测试角色权限，同时保留可用的本地恢复账号。|认证、权限映射与目录不可达时的行为符合预期。~登录失败逐项检查网络、TLS、绑定凭证、搜索条件和组映射。|systemctl status nslcd\njournalctl -b -u nslcd --no-pager\ngetent passwd
pid-thermal-tuning|PID 调参与失效保护|调参需要温度、PWM 和转速的时间序列。先测系统阶跃响应，再决定增益与采样周期。~积分项可能累积并导致输出饱和。Anti-windup、输出上下限和速率限制会改变最终响应。~原教程中的增益符号与具体误差定义有关。复制参数前应确认控制器实现中的误差方向。|误差计算~PID 输出~限幅与速率限制|记录固定环境和负载下的基线，保存 CSV 与配置版本。~逐项调整参数，每轮只改变可解释的一项并观察稳定时间。~验证传感器失效、低温和负载突变场景，检查 failsafe 和恢复。|系统响应稳定，温度约束与噪声目标同时满足，保护功能保持有效。~振荡先检查输入噪声、增益和延迟，长期饱和时检查积分项与限幅。|systemctl status phosphor-pid-control\njournalctl -b -u phosphor-pid-control --no-pager\nls /var/log
intrusion-detection-guide|机箱入侵、锁存与电池检测|实时入侵开关报告当前机箱状态，锁存电路保留曾经发生的事件。两者的清除和掉电行为不同。~电池移除检测可以使用实时比较器或跨掉电状态。原教程的扩展方案需要额外硬件和软件，不能视为所有 OpenBMC 平台已有功能。~涉及 VBAT 与持久化 token 时，必须测试读清顺序、断电条件和误报行为。|入侵开关~锁存状态~事件记录|先验证实时开关在 D-Bus 与 Redfish 中的状态映射。~若平台具备锁存或电池监测，再按电路设计分别验证掉电前后的记录。~记录事件清除与 token 更新顺序，核对是否出现重复或遗漏事件。|当前状态与历史事件可区分，掉电测试结果符合具体电路设计。~持续告警时检查极性、上拉和锁存清除，电池误报时检查上电时序与持久化状态。|gpioinfo\nsystemctl list-units '*intrusion*'\nls /sys/bus/nvmem/devices\njournalctl -b --no-pager -n 80
leak-detection|液冷漏液发现与保护动作|漏液监测由配置发现、GPIO 检测和事件记录组成。具体检测器接口和构建选项取决于 dbus-sensors 版本。~正常、漏液与检测不可用应有明确区分。单纯观察日志不能证明保护动作已经执行。~保护策略可能涉及关机或其他 target。实验应使用可控信号验证映射，避免在未知输入下触发整机动作。|检测器配置~GPIO 状态~事件与保护|核对检测器接线及有效电平，再确认配置接口与 daemon。~在实验平台模拟干燥和漏液信号，观察状态变化。~检查对应日志、target 与实际保护结果，并验证恢复条件。|检测状态、事件和保护动作一致，故障检测器不会显示为正常。~无对象时查配置类型和构建选项，有日志无动作时查 target 与策略绑定。|gpioinfo\nsystemctl list-units '*leak*'\njournalctl -b --no-pager -n 80
nvidia-gpu-management|GPU 旁带监控与控制|原教程介绍 dbus-sensors 中的 NVIDIA GPU 管理路径。具体设备发现和消息格式需要匹配当前组件及 GPU 固件。~MCTP endpoint 可达是传输层条件，温度、功率和控制能力仍取决于设备协议支持。~GPU 管理栈可能使用不同厂商组件。平台集成时先确认实际源码和 daemon，避免混用不同实现的接口。|MCTP endpoint~设备协议~GPU 对象|记录 GPU 及固件版本，确认平台使用的管理组件。~检查 endpoint 发现，再查看 GPU 库存与传感器对象。~在允许的实验条件下验证功率限制，并核对设备返回的结果。|传感器来源和控制范围明确，控制请求与设备实际状态一致。~发现成功但无读数时查协议版本与请求日志，写入被拒时查能力、范围和权限。|mctp link show\nmctp route show\nsystemctl list-units '*gpu*'\nbusctl list
`.trim().split('\n');
