export const rows = String.raw`
introduction|OpenBMC 与带外管理|BMC 是服务器上的独立管理控制器。主机操作系统失去响应时，只要管理控制器仍有供电和网络，管理员就能继续检查设备。~OpenBMC 为 BMC 提供 Linux 系统及管理服务。Yocto 构建镜像，systemd 管理服务，D-Bus 连接进程，Redfish 和 IPMI 提供外部接口。~学习时区分 Host、Chassis 和 BMC。重启管理控制器与重启主机影响不同，电源状态也不能混用。|管理网络~服务进程~物理设备|观察管理接口与主机接口的连接方式，标记独立供电、串口和控制信号。~在模拟器中访问管理接口，再查看 BMC 与 Host 的状态对象。~用同一份记录描述操作对象、请求状态和观察到的实际状态。|能解释管理请求最终经过哪些软件层，以及模拟器不能证明哪些硬件行为。~若接口可访问而主机操作无效，先检查平台是否实现了对应控制链路。|busctl list\nsystemctl --failed\ncat /etc/os-release
environment-setup|开发环境与构建隔离|完整镜像构建需要 Linux 环境、足够的内存和较大的磁盘空间。Windows 目录可以阅读源码，正式构建应放在合适的 Linux 文件系统。~原教程介绍原生 Linux、容器与 SDK。容器固定宿主依赖，SDK 用于单个应用交叉编译，首次生成 SDK 仍需要完整构建。~下载缓存与 sstate 缓存用途不同。团队应记录源码版本、容器版本和 machine，避免只记录一次成功的命令。|Linux 主机~构建容器~目标镜像|检查 CPU、内存、磁盘与 locale，确认构建目录可写。~选择原生 Linux 或容器，并按照源教程安装该发行版对应依赖。~初始化构建环境后保存配置和版本信息，先做一次小范围构建。|能够重复进入同一构建环境，且缓存目录在容器退出后仍然存在。~内存耗尽时降低并行度，磁盘不足时先定位下载、工作目录和缓存占用。|uname -a\nfree -h\ndf -h\nlocale\ngit rev-parse HEAD
first-build|首次构建与 QEMU 启动|machine 决定设备树、内核配置和平台服务。初始化环境前先确认目标名称，再构建 obmc-phosphor-image。~第一次构建包含源代码下载和大量宿主工具编译。一次网络错误不代表配方本身错误，应从失败任务的日志判断原因。~启动 QEMU 时，镜像、模拟机型和网络转发需要匹配。能够登录 BMC 只说明软件启动成功，不能代替真板电源或风扇验证。|配置 machine~构建镜像~启动模拟器|按原教程的 setup 命令选择 QEMU 对应 machine，在初始化后的 shell 内运行构建。~从 tmp/deploy/images 下确认镜像名、大小和生成时间。~用匹配的 QEMU machine 启动，记录串口启动日志并查询 Redfish 服务根。|串口出现登录提示，管理接口可访问，核心服务没有持续崩溃。~无法连接时依次检查进程、端口转发、监听端口、登录凭证与服务日志。|bitbake obmc-phosphor-image\nbitbake -e obmc-phosphor-image\nqemu-system-arm -machine help
development-workflow|配方、补丁与增量开发|应用代码、BitBake 配方和平台配置属于不同修改位置。应用行为变化应修改源代码，平台差异通常通过自有 layer 和 bbappend 表达。~devtool 将配方源码放入开发工作区，适合反复编辑和增量构建。finish 将修改整理到指定 layer，执行前应检查补丁和工作区状态。~sstate 复用已完成任务的结果。缓存是否命中取决于任务输入与签名，不能用缓存目录大小判断效果。|源代码~配方元数据~平台 layer|选择一个小型服务，记录原始 SRCREV 与当前配方。~使用 devtool modify 和 devtool build 修改、构建，再在测试目标验证。~审查补丁内容和 bbappend 路径，确认干净构建仍能获得相同行为。|补丁在工作区之外也能复现，配方命名与匹配规则正确。~更改没有生效时检查实际 SRCREV、配方覆盖、workspace 和构建任务日志。|devtool status\nbitbake-layers show-layers\nbitbake-layers show-appends
building-qemu|QEMU 版本与机型支持|系统提供的 QEMU 不一定包含所需 ASPEED machine。先检查版本和 machine 列表，缺失时再选用构建系统提供的 QEMU 或源码构建。~模拟 CPU 架构与镜像必须兼容。AST2500、AST2600 等机型名称及支持范围取决于 QEMU 版本。~模拟器适合验证服务、接口与部分驱动路径。模拟的器件数量、时序和错误行为与实板可能不同。|QEMU 可执行文件~machine 模型~Flash 镜像|找出当前实际执行的 QEMU 路径，记录其版本。~查询可用 machine 列表并与源教程启动参数逐项对照。~保存一份启动脚本，明确镜像路径、串口输出和网络转发。|重启实验时可以复现同一模拟环境，且启动脚本没有隐式依赖当前目录。~Machine type not found 时检查调用到的二进制，避免误用另一版本。|which qemu-system-arm\nqemu-system-arm --version\nqemu-system-arm -machine help
devtool-workflow-guide|devtool 部署与调试闭环|开发闭环包含提取源码、修改、构建、部署、重启服务和验证。构建成功只代表产物生成，目标系统仍可能运行旧文件。~部署前确认目标架构、动态库依赖与服务名。临时部署适合测试，最终应通过配方生成镜像。~gdbserver 与交叉 GDB 需要匹配的符号和源码。调试日志、二进制和源码版本应成套保存。|workspace~目标服务~调试符号|在模拟器上选择可恢复的服务，先保存原文件与服务状态。~修改一条可观察行为并增量构建，部署后确认文件时间与实际进程。~对目标设置断点或读取日志，记录验证结果后将修改整理为补丁。|服务表现与代码修改一致，镜像重新构建后仍然保持该行为。~服务启动失败时检查 ELF 架构、共享库、D-Bus 名称冲突与 systemd 日志。|devtool status\nfile ./service-binary\nsystemctl status phosphor-state-manager*\njournalctl -b --no-pager -n 50
gerrit-contribution-guide|Gerrit 评审与提交身份|OpenBMC 的贡献流程将代码评审、提交身份和 CI 结果关联起来。提交消息应说明问题、行为变化和验证方式。~Change-Id 用于关联同一评审的不同 patch set。修订已有评审时保留该标识，避免形成互不关联的新评审。~内核改动需要结合上游贡献流程和项目政策。记录上游链接及适用版本，有助于减少长期本地补丁维护。|Git 提交~Gerrit patch set~CI 结果|核对 Git 身份与 Gerrit 账户的登记邮箱。~在本地检查提交消息中的 Sign-off 与 Change-Id，按教程配置 commit-msg hook。~阅读评审和 CI 日志，对失败进行本地复现后再更新提交。|提交说明能让未参与讨论的评审者理解修改原因和验证范围。~缺少 Change-Id 时检查 hook，身份不匹配时检查 committer 邮箱。|git config user.name\ngit config user.email\ngit log -1 --format=fuller\ngit status --short
openbmc-overview|OpenBMC 软件分层|外部请求通常进入 bmcweb 或 IPMI 服务，再读取或修改 D-Bus 对象。底层服务通过 Linux 驱动访问硬件。~meta-phosphor 提供通用能力，SoC layer 提供芯片支持，平台 layer 保存板级差异。层次关系决定了修改放在哪里。~故障定位应沿数据路径逐层检查。网页没有温度读数时，先确认 API、D-Bus、hwmon 和驱动各层的实际输出。|外部接口~D-Bus 服务~内核驱动|从当前仓库列出通用、SoC 与平台 layer，并查找一个目标配方。~选择一个管理对象，记录其 Redfish 路径、D-Bus 接口及后端服务。~找到该服务的启动单元与日志，画出实际调用关系。|能够从一个用户可见功能追踪到服务和硬件依赖。~不要根据目录名推断配方最终来源，使用 bitbake-layers 与 bitbake -e 确认。|bitbake-layers show-layers\nbitbake-layers show-recipes\nbusctl list\nsystemctl --failed
d-bus-guide|D-Bus 对象模型与 Object Mapper|一个 D-Bus 对象由服务名、对象路径和接口描述。属性表达当前数据，方法表达操作，信号表达异步变化。~OpenBMC 的服务归属可能随对象和实现变化。Object Mapper 按对象路径与接口查询拥有者，客户端应避免写死所有服务名。~类型签名约束参数与返回值。busctl 调用失败时应先 introspect，再核对接口、成员和签名。|服务名~对象路径~接口与成员|使用 busctl list 找到运行服务，再用 tree 查看对象路径。~选择一个对象进行 introspect，读取属性并解释类型签名。~监视一次实际变化，比较调用结果与 PropertiesChanged 信号。|能区分对象不存在、接口不存在、属性类型错误与权限失败。~UnknownObject 时查 Mapper 和对象生命周期，AccessDenied 时检查总线策略与调用身份。|busctl list\nbusctl tree xyz.openbmc_project.ObjectMapper\nbusctl introspect xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper
state-manager-guide|BMC、机箱与主机状态|BMCState、ChassisState 与 HostState 描述不同对象。RequestedTransition 表达请求，CurrentState 表达实际结果，二者存在时间差。~电源控制由状态服务、systemd target 和板级 GPIO 配合完成。服务接受请求后仍需要实际电源反馈证明操作完成。~恢复策略、启动进度与 watchdog 会影响自动行为。分析重启应把请求、状态迁移和触发来源放在同一时间线上。|状态请求~systemd target~硬件反馈|查看 BMC、Chassis 和 Host 的状态对象，记录路径和属性值。~在测试平台发起一次受控转换，同时采集状态与服务日志。~检查转换失败或超时后的状态，确认恢复策略没有隐藏真实故障。|请求后的实际状态与硬件反馈一致，日志能说明转换过程。~卡在 Quiesced 时结合故障日志、目标依赖和恢复策略定位，避免反复重启掩盖原因。|obmcutil state\nbusctl tree xyz.openbmc_project.State.Host\nsystemctl list-units 'obmc*'\njournalctl -b -n 60 --no-pager
custom-d-bus-services-guide|自定义 D-Bus 服务|服务开发从接口契约开始。YAML 定义属性、方法与错误，sdbusplus 生成绑定，应用实现处理逻辑。~同步服务和基于 Boost.Asio 的异步服务适合不同负载。回调中阻塞会拖慢事件处理，异步对象的生命周期需要明确。~服务还需要 systemd 单元、D-Bus 策略与 Yocto 配方。二进制成功编译后仍要确认服务名和接口真正可见。|接口 YAML~服务实现~打包与启动|参考原教程的 Greeter 示例，先定义一个只读属性和一个简单方法。~编译部署到 QEMU，并检查服务启动、名称注册和对象发布。~通过 busctl 验证属性与方法，再重启服务观察对象恢复。|接口行为与 YAML 契约一致，错误输入得到可解释的错误返回。~Name already taken 时查重复实例，属性不可见时查对象发布和接口注册顺序。|busctl list\nsystemctl --failed\njournalctl -b -u phosphor-greeter --no-pager
systemd-boot-ordering-guide|systemd 依赖与启动顺序|Wants 和 Requires 决定依赖拉起及失败关系。After 和 Before 决定顺序，单独设置 After 不会自动启动另一服务。~进程启动与服务就绪存在区别。客户端可能需要等待 D-Bus 名称或对象出现，不能只依赖某个进程已经运行。~模板单元通过实例参数服务多个 Host。oneshot 的执行结果和 RemainAfterExit 会影响后续状态观察。|依赖关系~执行顺序~就绪条件|选择一个服务，查看 Unit 中的 Wants、Requires、After 与 Before。~用 critical-chain 找到启动关键路径，再与该服务日志对照。~检查一个模板实例，确认实例编号与 Host 编号一致。|能够解释服务为何启动、何时启动，以及失败如何影响依赖者。~服务未拉起时查依赖链接，过早访问对象时查就绪条件和客户端重试。|systemctl cat phosphor-mapper.service\nsystemd-analyze critical-chain\nsystemd-analyze blame\nsystemctl list-dependencies
d-bus-sensors-guide|传感器数据发布与阈值|dbus-sensors 的多个 daemon 处理不同器件类型。配置匹配后，服务读取硬件数据并创建传感器对象。~Sensor.Value、单位、量程和阈值共同描述读数。数值正确但单位或缩放错误，同样会造成管理接口误判。~告警触发与恢复通常需要考虑滞回和电源状态。断电期间的无效读数不应直接当作真实过温。|硬件采样~传感器对象~阈值事件|从 hwmon 或设备接口确认一项原始读数，再找到对应 D-Bus 对象。~核对单位、缩放、量程与阈值配置，再查询外部接口。~在可控测试输入下观察告警触发和恢复，记录滞回区间。|内核、D-Bus 和管理接口读数一致，告警行为符合设定。~传感器缺失时检查 Probe、Type、daemon 是否打包及电源状态过滤。|ls /sys/class/hwmon\nbusctl tree xyz.openbmc_project.HwmonTempSensor\nsystemctl list-units '*sensor*'
hwmon-sensors-guide|Linux hwmon 与温度单位|hwmon 将驱动数据暴露到 sysfs。温度、风扇和电压的属性名与单位由 Linux hwmon ABI 定义。~hwmon 目录编号可能随探测顺序变化。通过 name 和实际设备路径确认器件，不能长期依赖 hwmon0 代表某个固定传感器。~phosphor-hwmon 和 dbus-sensors 的配置方式不同。迁移时应核对服务、对象名、阈值与配置来源。|芯片驱动~hwmon 属性~OpenBMC 传感器服务|列出所有 hwmon name，将每个目录关联到实际总线器件。~读取一个 temp*_input，并按该属性的 ABI 单位换算。~比较 D-Bus 发布值和 hwmon 值，解释正常采样时间差。|能把一个外部读数追踪到具体 sysfs 文件和驱动。~数值差一千倍时检查毫度与摄氏度转换，设备缺失时查驱动绑定。|grep . /sys/class/hwmon/hwmon*/name\nfind /sys/class/hwmon -name 'temp*_input'\ndmesg | tail -n 40
entity-manager-guide|Entity Manager 硬件发现|Entity Manager 根据 Probe 匹配硬件记录，并把 Exposes 配置发布到 D-Bus。它提供硬件描述，传感器 daemon 负责实际采样。~JSON 的语法正确只证明文件可解析。Probe 条件、接口类型、总线和地址仍需与真实硬件及当前实现匹配。~FRU 信息可驱动动态配置。热插拔和重载需要同时观察发现记录、配置对象以及消费配置的服务。|Probe 匹配~Exposes 发布~配置消费|选择一个已有平台 JSON，解释 Name、Probe 与 Exposes 的作用。~在测试目标确认 Probe 所引用的 D-Bus 信息真实存在。~观察 Entity Manager 日志，再确认传感器 daemon 是否创建对应对象。|配置对象与实际设备一致，传感器服务能消费该配置。~Probe 不匹配时先检查原始 FRU 或发现属性，避免直接改成无条件匹配掩盖问题。|journalctl -b -u entity-manager --no-pager\nbusctl tree xyz.openbmc_project.EntityManager\nls /usr/share/entity-manager/configurations
fan-control-guide|风扇区域与闭环控制|风扇控制把温度输入、控制策略与 PWM 输出组织为 zone。一个 zone 可以包含多个温度来源和多个风扇。~手动 PWM 只适合受控测试。自动控制需要有效输入、合理下限和失效保护，以覆盖传感器失联或风扇异常。~PID 参数与 stepwise 策略影响噪声、温度和响应速度。调参前先记录基线，不要仅凭静态温度判断稳定性。|温度输入~控制 zone~PWM 与转速反馈|核对温度、风扇转速和 PWM 对象是否属于同一散热区域。~在测试平台记录自动模式下温度、输出和转速的变化。~验证无效输入后的 failsafe，测试结束后确认自动模式恢复。|负载变化时温度与风扇输出响应合理，失联时进入定义的保护状态。~满速运行时检查输入有效性与 failsafe，振荡时检查增益、采样周期和速率限制。|systemctl status phosphor-pid-control\njournalctl -b -u phosphor-pid-control --no-pager\nls /sys/class/hwmon
power-management-guide|电源时序与 PSU 反馈|开机涉及请求、使能信号、供电轨与 Power Good。状态服务需要根据实际反馈判断是否成功。~PSU 监控与电压调节器管理承担不同任务。平台配置需要匹配 PMBus 器件、寄存器定义和电源拓扑。~功率限制、冗余策略和掉电恢复策略会影响整机行为。观察异常应包含负载、电源状态和策略设置。|开机请求~电源控制~Power Good|整理原理图中的电源使能、Power Good 与 PSU presence 信号。~从日志观察一次受控开机，按时间记录各级状态。~检查 PSU 告警、冗余变化与恢复策略，确认故障路径可观测。|开机完成条件来自实际反馈，PSU 故障能产生可追踪事件。~电源启动失败时检查 GPIO 极性、时序和 PSU 状态，而非只查看 HostState。|obmcutil state\nsystemctl list-units '*power*'\njournalctl -b --no-pager -n 80\ncat /proc/interrupts
user-manager-guide|用户、角色与账号策略|phosphor-user-manager 管理本地用户及权限映射。Redfish 角色、D-Bus 权限和 IPMI 通道权限需要一致检查。~账号锁定和密码策略影响登录流程。身份认证成功与操作授权成功是两个独立检查点。~会话、LDAP 与 MFA 等能力取决于版本和平台配置。不要把教程中的可选功能视为所有镜像默认提供。|认证身份~角色权限~管理会话|用测试账号查询其角色与通道权限，记录可访问接口。~分别验证只读用户和管理员的预期操作权限。~观察账号锁定、会话退出和策略持久化行为。|低权限账号只能执行允许操作，策略变更与日志一致。~认证通过但操作失败时查权限映射，所有登录失败时检查账号状态与 PAM 日志。|busctl tree xyz.openbmc_project.User.Manager\nsystemctl status phosphor-user-manager\njournalctl -b --no-pager -n 60
network-guide|管理网络、DHCP 与 NCSI|phosphor-network 管理网络配置并与 systemd-networkd 等组件协作。IP 地址、路由和 DNS 分别影响不同连接阶段。~专用管理网口和 NCSI 共享网络路径有不同硬件依赖。链路 up 并不保证地址、路由和上游交换机配置正确。~静态 IP、VLAN 或 MAC 修改可能中断当前管理连接。实验前保留串口访问，并记录原始配置。|链路~地址与路由~管理服务|通过串口记录接口、地址、路由和 DNS。~在测试网络验证 DHCP 或静态配置，再测试本地与跨网段访问。~重启后确认配置持久化，NCSI 平台同时检查 channel 与 package 状态。|地址与路由符合预期，管理服务在配置完成后可访问。~按链路、地址、路由、DNS、监听端口顺序定位，避免把所有失败归为网络服务问题。|ip link\nip address\nip route\nnetworkctl status\nresolvectl status
led-manager-guide|LED 物理驱动与逻辑组|物理 LED 由 GPIO 或其他驱动控制，逻辑 LED group 表达定位、故障和电源等管理含义。~组优先级决定多个状态同时要求同一灯时的结果。验证单个 LED 亮灭不足以证明组合策略正确。~JSON 运行配置与 YAML 编译配置可能并存。实际使用哪种方式取决于当前配方和服务实现。|逻辑状态~LED group~物理 LED|建立逻辑组与物理灯的映射表，核对极性和默认状态。~检查定位组及故障组的配置，观察组合状态的优先级。~重启后验证默认状态和策略恢复，再检查外部接口表达。|实际灯光状态符合逻辑组与优先级，重启后没有异常闪烁。~D-Bus 正常而灯不变化时查 sysfs、GPIO 与驱动，组未生效时查配置格式和路径。|ls /sys/class/leds\nbusctl tree xyz.openbmc_project.LED.GroupManager\nsystemctl list-units '*led*'
certificate-manager-guide|证书链、CSR 与服务重载|HTTPS 证书需要与私钥配对，证书链需要连接到客户端信任的根。自签名证书适合隔离实验，部署环境应使用合适的信任体系。~证书中的主机名和有效期会影响客户端验证。系统时间错误也会造成证书未生效或过期。~替换证书后需要确认服务实际加载了新证书。文件更新成功不等于客户端已经看到新身份。|私钥与 CSR~证书链~HTTPS 服务|读取当前服务器证书的主题、SAN 和有效期。~按源教程在实验平台完成 CSR 或证书替换。~重新建立 TLS 连接，确认服务器呈现的证书指纹已变化。|客户端按预期验证证书链、名称与时间，服务恢复后仍使用新证书。~验证失败时分别检查时间、SAN、链完整性与信任根。|openssl x509 -in server.pem -noout -subject -issuer -dates\nopenssl x509 -in server.pem -noout -fingerprint -sha256\ntimedatectl
time-manager-guide|系统时钟、RTC 与 NTP|时间管理协调系统时钟、RTC、NTP 与可能的主机时间来源。多个写入方同时校时会造成跳变。~NTP 启用与已同步需要分开检查。网络、DNS 和时间服务状态都会影响同步结果。~事件日志、证书验证和故障关联依赖可靠时间。记录测试数据时应明确时区和时间源。|时间来源~系统时钟~日志时间戳|读取当前时间、时区与同步状态，并记录 RTC 状态。~检查 NTP 服务器可达性和时间服务日志。~重启后确认时间恢复来源，比较事件日志与测试机时间。|时间持续同步且事件顺序可靠，重启后的时间来源明确。~证书错误或日志乱序时先排查时钟跳变，再检查上层服务。|date -u\ntimedatectl\ntimedatectl timesync-status\nhwclock -r
inventory-manager-guide|Inventory、FRU 与关联关系|Inventory 表达设备身份、位置和存在状态。FRU 提供制造商、型号、序列号等可替换部件信息。~Association 将传感器、库存项与机箱关系连接起来。外部接口常依赖这些关系组织资源。~EEPROM 内容、D-Bus 库存对象和 Redfish 资源需要保持一致。设备不存在时应检查状态表达，而非仅删除读数。|FRU 数据~库存对象~资源关联|读取一项 FRU，并核对板卡上的型号或序列号。~在 D-Bus 中找到对应库存项，记录 Present 等属性。~检查传感器关联和外部资源归属，解释设备插拔时的变化。|库存身份、存在状态和传感器归属一致。~FRU 可读但资源缺失时查发现服务、配置 Probe 与 Association。|busctl tree xyz.openbmc_project.Inventory.Manager\nipmitool fru print\nsystemctl list-units '*fru*'
watchdog-guide|Watchdog 超时与恢复动作|Watchdog 通过定期刷新证明受监控方仍在正常运行。计时器配置包含超时、启用状态和到期动作。~主机 watchdog 与 BMC 自身 watchdog 的对象和影响不同。测试前确认究竟会重置哪一部分。~到期动作需要结合电源状态服务与平台能力验证。定时器到期但没有动作时，检查完整恢复链路。|启用计时器~定期刷新~超时动作|在可恢复实验平台记录 watchdog 当前参数与监控对象。~按教程观察刷新后的剩余时间或日志，不先改变生产策略。~设计短时故障测试并验证到期动作，测试后恢复原参数。|计时器、日志与实际恢复动作一致，正常刷新不会触发误重启。~频繁重启时核对刷新来源、超时值、启动阶段和重复控制者。|ipmitool mc watchdog get\nsystemctl list-units '*watchdog*'\njournalctl -b --no-pager -n 60
buttons-guide|按钮事件与主机动作|按钮输入经过 GPIO 或 input 子系统，再由用户态服务解释按压和释放。事件极性与电气接线必须一致。~短按、长按和去抖策略表达不同操作意图。若硬件与服务同时处理同一信号，可能产生重复动作。~按钮触发的电源操作最终仍需状态反馈。日志应关联输入事件、目标动作与实际结果。|按钮输入~事件解释~状态操作|根据原理图核对输入引脚、上拉和有效电平。~观察一次短按和释放的事件，记录时间与目标变化。~在实验平台验证长按或去抖行为，并检查是否出现重复触发。|一次按压对应预期动作，抖动不会导致多次转换。~没有事件时查 pinmux 和 input/GPIO 路径，动作重复时查多个消费者。|gpioinfo\ncat /proc/bus/input/devices\nsystemctl list-units '*button*'
gpio-management-guide|GPIO line 名称与事件监控|GPIO line 名称能把软件配置与原理图信号对齐。不同 gpiochip 的 offset 不能混作统一编号。~phosphor-multi-gpio-monitor 将边沿事件映射到 systemd target。持续监控和一次性监控适合不同场景。~GPIO 输出的逻辑值、active-low 和物理电平有区别。修改前应确认信号方向和占用者。|line 名称~边沿事件~目标单元|通过 gpioinfo 找到目标信号，核对 chip、offset 和消费者。~阅读 JSON 监控配置，确认 LineName、事件类型与目标实例。~在可控输入下观察边沿和日志，再验证重复事件行为。|软件名称对应正确引脚，事件与 target 触发一致。~Line busy 时查消费者，首次有效后失效时检查 OneShot 等配置。|gpioinfo\nsystemctl list-units '*gpio*'\njournalctl -b --no-pager -n 60
peci-thermal-monitoring|Intel PECI 温度采集|PECI 提供与支持该接口的 CPU 通信的旁带路径。温度来源和换算方式不同于普通 I2C 温度芯片。~完整链路包含控制器、客户端驱动、hwmon 与传感器 daemon。Host 电源状态会影响可读数据。~DIMM 温度和部分 CPU 指标依赖处理器支持及固件状态。QEMU 的接口验证不能证明真板 PECI 时序正确。|PECI 控制器~CPU 客户端~温度对象|核对 PECI 接线、电源条件与 CPU 地址。~检查内核驱动及 hwmon 名称，再观察原始温度。~对照 D-Bus 与 Redfish，记录 Host 不同状态下的读数有效性。|温度来源、单位和可用状态可解释，主机断电时不产生误告警。~Ping 失败先查物理与供电，hwmon 缺失再查驱动、设备树和内核配置。|dmesg | grep -i peci\nls /sys/bus/peci/devices\ngrep . /sys/class/hwmon/hwmon*/name
i2c-device-integration|I2C 拓扑、地址与驱动绑定|I2C 设备定位需要同时确认总线与地址。mux 下的逻辑总线编号可能与原理图控制器编号不同。~设备树的 compatible 选择驱动，reg 表达地址。地址可响应只说明存在设备，不能证明驱动和寄存器格式正确。~运行时绑定适合诊断，正式平台应以设备树和配方保存配置。扫描或寄存器访问前先确认器件允许相应操作。|控制器与 mux~设备地址~内核驱动|绘制控制器、mux 通道和设备的对应关系，核对原理图。~只先列出总线和已绑定设备，确认驱动及内核日志。~按数据手册验证读数，再连接 hwmon 与 Entity Manager 配置。|目标设备绑定正确驱动，读数符合数据手册，重启后配置仍成立。~ENXIO 时查地址与供电，读数异常时查驱动、字节序和 mux 路径。|i2cdetect -l\nls /sys/bus/i2c/devices\ndmesg | grep -i i2c
psu-pmbus-management|PSU 监控与 PMBus 状态|PMBus 为电源设备提供监控与控制命令。具体支持命令、数据格式和故障位需要参考器件资料。~PSU presence、输入电源状态与输出故障表达不同事实。冗余策略需要基于实际在线且健康的电源数量。~内核 PMBus 驱动、PSU 传感器服务和 phosphor-power 各有职责，应逐层确认。|PMBus 设备~功率与状态~冗余策略|核对 PSU 型号、地址与驱动支持，记录固件版本。~检查 hwmon 原始数据和 D-Bus 对象，对照负载条件。~在实验机上观察 PSU presence 或输入变化，确认库存与故障日志一致。|读数与电源状态一致，冗余丢失产生预期事件。~缺少数据时查驱动与配置，数值异常时查 LINEAR 格式、单位和支持命令。|grep . /sys/class/hwmon/hwmon*/name\nsystemctl list-units '*psu*'\njournalctl -b --no-pager -n 80
ldap-integration|LDAP 认证与角色映射|LDAP 让管理控制器使用目录服务进行身份验证。PAM、nslcd、目录配置与本地角色映射共同决定登录结果。~LDAPS 需要正确的 CA 信任、服务名称和系统时间。连接成功后仍要检查搜索基准、绑定账号与组查询。~目录组映射到 BMC 角色后，还需验证具体接口权限。不能只以一次管理员登录成功作为验收。|目录查询~身份认证~组权限映射|在测试目录建立低权限与管理员组，记录搜索基准与组属性。~验证 TLS 连接，再检查 nslcd 和 PAM 日志。~分别登录并测试角色权限，同时保留可用的本地恢复账号。|认证、权限映射与目录不可达时的行为符合预期。~登录失败逐项检查网络、TLS、绑定凭证、搜索条件和组映射。|systemctl status nslcd\njournalctl -b -u nslcd --no-pager\ngetent passwd
pid-thermal-tuning|PID 调参与失效保护|调参需要温度、PWM 和转速的时间序列。先测系统阶跃响应，再决定增益与采样周期。~积分项可能累积并导致输出饱和。Anti-windup、输出上下限和速率限制会改变最终响应。~原教程中的增益符号与具体误差定义有关。复制参数前应确认控制器实现中的误差方向。|误差计算~PID 输出~限幅与速率限制|记录固定环境和负载下的基线，保存 CSV 与配置版本。~逐项调整参数，每轮只改变可解释的一项并观察稳定时间。~验证传感器失效、低温和负载突变场景，检查 failsafe 和恢复。|系统响应稳定，温度约束与噪声目标同时满足，保护功能保持有效。~振荡先检查输入噪声、增益和延迟，长期饱和时检查积分项与限幅。|systemctl status phosphor-pid-control\njournalctl -b -u phosphor-pid-control --no-pager\nls /var/log
intrusion-detection-guide|机箱入侵、锁存与电池检测|实时入侵开关报告当前机箱状态，锁存电路保留曾经发生的事件。两者的清除和掉电行为不同。~电池移除检测可以使用实时比较器或跨掉电状态。原教程的扩展方案需要额外硬件和软件，不能视为所有 OpenBMC 平台已有功能。~涉及 VBAT 与持久化 token 时，必须测试读清顺序、断电条件和误报行为。|入侵开关~锁存状态~事件记录|先验证实时开关在 D-Bus 与 Redfish 中的状态映射。~若平台具备锁存或电池监测，再按电路设计分别验证掉电前后的记录。~记录事件清除与 token 更新顺序，核对是否出现重复或遗漏事件。|当前状态与历史事件可区分，掉电测试结果符合具体电路设计。~持续告警时检查极性、上拉和锁存清除，电池误报时检查上电时序与持久化状态。|gpioinfo\nsystemctl list-units '*intrusion*'\nls /sys/bus/nvmem/devices\njournalctl -b --no-pager -n 80
leak-detection|液冷漏液发现与保护动作|漏液监测由配置发现、GPIO 检测和事件记录组成。具体检测器接口和构建选项取决于 dbus-sensors 版本。~正常、漏液与检测不可用应有明确区分。单纯观察日志不能证明保护动作已经执行。~保护策略可能涉及关机或其他 target。实验应使用可控信号验证映射，避免在未知输入下触发整机动作。|检测器配置~GPIO 状态~事件与保护|核对检测器接线及有效电平，再确认配置接口与 daemon。~在实验平台模拟干燥和漏液信号，观察状态变化。~检查对应日志、target 与实际保护结果，并验证恢复条件。|检测状态、事件和保护动作一致，故障检测器不会显示为正常。~无对象时查配置类型和构建选项，有日志无动作时查 target 与策略绑定。|gpioinfo\nsystemctl list-units '*leak*'\njournalctl -b --no-pager -n 80
nvidia-gpu-management|GPU 旁带监控与控制|原教程介绍 dbus-sensors 中的 NVIDIA GPU 管理路径。具体设备发现和消息格式需要匹配当前组件及 GPU 固件。~MCTP endpoint 可达是传输层条件，温度、功率和控制能力仍取决于设备协议支持。~GPU 管理栈可能使用不同厂商组件。平台集成时先确认实际源码和 daemon，避免混用不同实现的接口。|MCTP endpoint~设备协议~GPU 对象|记录 GPU 及固件版本，确认平台使用的管理组件。~检查 endpoint 发现，再查看 GPU 库存与传感器对象。~在允许的实验条件下验证功率限制，并核对设备返回的结果。|传感器来源和控制范围明确，控制请求与设备实际状态一致。~发现成功但无读数时查协议版本与请求日志，写入被拒时查能力、范围和权限。|mctp link show\nmctp route show\nsystemctl list-units '*gpu*'\nbusctl list
`.trim().split('\n');
rows.push(...String.raw`
ipmi-guide|IPMI 命令与 provider|IPMI 通过 NetFn、命令号和数据字段表达请求。网络 LAN 与本地主机 KCS、BT 或 SSIF 使用不同传输路径。~ipmid 使用 provider 注册命令处理逻辑。OEM 命令需要明确权限、参数长度和完成码，避免返回无法解释的数据。~SDR 描述传感器，SEL 记录事件。读取值、发现传感器和查看历史告警属于不同操作。|传输接口~命令派发~D-Bus 后端|先查询设备身份、SDR 和 SEL，建立只读操作基线。~追踪一条命令对应的 provider 与 D-Bus 接口。~在模拟器开发简单 OEM 示例，验证错误参数、权限和完成码。|标准与 OEM 命令返回结构正确，未支持命令得到明确完成码。~远程失败时查网络会话和 cipher，命令未知时查 provider 打包与注册。|ipmitool mc info\nipmitool sdr list\nipmitool sel info\nsystemctl list-units '*ipmi*'
redfish-guide|Redfish 资源与 HTTP 语义|Redfish 用资源 URI、JSON 模式与 HTTP 方法表达管理功能。Collection 中的 Members 链接应从服务响应发现。~bmcweb 将 D-Bus 后端对象映射为资源。接口返回成功与硬件操作完成需要区分，异步任务要继续查询状态。~会话认证、权限和证书验证共同决定访问能力。示例地址、凭证和资源 ID 必须替换为目标系统实际值。|HTTPS 请求~bmcweb 路由~D-Bus 查询|查询 ServiceRoot，沿 Members 链接找到 Systems、Managers 和 Chassis。~比较一个资源的 GET 响应与对应 D-Bus 属性。~在实验环境验证错误 URI、低权限账号和异步操作的返回。|资源标识、单位、错误对象与状态码符合接口契约。~404 时检查链接和功能启用，403 时检查权限，500 时查后端调用日志。|curl --cacert ca.pem -u USER https://BMC/redfish/v1/\nsystemctl status bmcweb\njournalctl -b -u bmcweb --no-pager
webui-guide|WebUI 数据流与界面调试|webui-vue 的界面通过 Redfish 等接口读取数据。浏览器显示异常应先观察实际网络请求。~界面状态、后端资源和会话状态需要一致。前端页面加载成功不代表业务 API 已返回有效数据。~品牌、语言和导航定制应通过项目现有机制保存。构建产物还需要正确部署到静态资源路径。|浏览器视图~API 请求~后端资源|用浏览器开发者工具记录一次页面加载的请求与响应。~将失败请求独立复现，判断问题来自接口还是前端状态。~按源教程增加测试页面或翻译，构建后验证会话与错误显示。|页面能正确处理加载、失败和权限不足，数据显示与 API 一致。~空白页查控制台与资源路径，登录循环查 token、cookie、证书和会话超时。|systemctl status bmcweb\njournalctl -b -u bmcweb --no-pager\nls /usr/share/www
kvm-guide|远程 KVM 视频与 USB 输入|KVM 包含视频采集、编码与网络传输，也包含键盘和鼠标的 USB HID 输入路径。两条路径可能分别失败。~obmc-ikvm、bmcweb WebSocket 代理及浏览器客户端共同提供远程会话。视频设备和 USB gadget 依赖平台硬件。~黑屏可能来自主机无视频输出、采集驱动或会话链路。QEMU 无法替代完整真板视频验证。|视频采集~网络会话~USB HID 输入|确认视频设备、采集驱动和 USB 设备控制器已经启用。~连接实验机 KVM，分别验证图像更新、键盘与鼠标。~测试 BIOS 与操作系统阶段，记录断连、分辨率变化和会话释放。|视频与输入两条路径分别通过，断连后资源正常释放。~有图无输入查 HID gadget，完全黑屏查主机输出和采集设备日志。|ls /dev/video*\nls /sys/class/udc\nsystemctl status obmc-ikvm\njournalctl -b -u obmc-ikvm --no-pager
virtual-media-guide|虚拟介质与 USB 存储|虚拟介质把网络或浏览器提供的镜像映射为主机可见的存储设备。代理模式与旧模式的服务和传输不同。~挂载成功、主机识别成功与主机可启动是三个验证阶段。启动还受镜像格式和 BIOS 设置影响。~会话结束后应释放 NBD 和 gadget 等资源。测试记录需要包含镜像校验值和挂载方式。|镜像来源~代理与 NBD~USB gadget|确认平台支持的虚拟介质模式和 USB 设备控制器。~在实验主机挂载已知可启动镜像，核对 BMC 状态和 Host 设备识别。~完成读盘和启动验证后卸载，确认设备与会话资源释放。|主机读到正确镜像，卸载后不残留占用，下一次挂载可重复成功。~BMC 已挂载而主机无设备时查 gadget，设备出现但不能启动时查镜像与启动顺序。|ls /sys/class/udc\nls /sys/kernel/config/usb_gadget\nsystemctl list-units '*virtual*'\nsystemctl list-units '*nbd*'
console-guide|主机串口与 SOL|BMC 控制台与 Host 控制台是不同串口。obmc-console-server 读取指定 Host UART，并向客户端提供访问。~波特率、VUART 设置与主机固件串口配置需要一致。乱码通常来自速率或串口参数不匹配。~SOL、SSH 控制台与 WebUI 可能共享同一后端。日志记录应考虑敏感输出与轮转容量。|Host UART~console-server~远程客户端|确认原理图及设备树中的 Host UART，核对主机固件串口设置。~先验证本地后端，再分别测试 SOL 和浏览器访问。~测试断连重连、多个客户端及日志轮转，记录退出方式。|启动阶段输出连续，输入到达正确主机，客户端退出后后端仍正常。~无输出先查串口来源与主机配置，冻结时检查流控、消费者和 mux 状态。|ls /dev/ttyS*\nsystemctl list-units '*console*'\nipmitool sol info\njournalctl -b --no-pager -n 60
ssh-security-guide|SSH 身份与主机密钥|SSH 客户端验证服务器主机密钥，服务器验证用户身份。主机密钥变化与用户公钥拒绝属于不同故障。~Dropbear 与 OpenSSH 的配置选项和能力不同。PAM、账号策略和 authorized_keys 权限都可能影响认证。~服务配置变更可能切断远程访问。先保留串口和测试账号，再在实验环境验证新策略。|主机身份~用户认证~会话策略|记录服务类型、监听端口和主机密钥指纹。~使用测试账号验证公钥登录和账号权限。~检查密码策略、会话超时与日志，再验证重启后的配置持久化。|用户只获得预期权限，客户端能够校验稳定的服务器身份。~公钥拒绝时查文件权限和格式，连接拒绝时查服务监听与防火墙。|ss -lntp\nsystemctl status dropbear\nsystemctl status sshd\njournalctl -b --no-pager -n 60
redfish-events-telemetry|事件推送、SSE 与遥测|EventService 推送事件，SSE 提供持续事件流，TelemetryService 按定义采集指标。它们的生命周期和负载不同。~订阅包含目的地址、筛选条件和重试策略。服务器创建订阅成功后，还需要确认目的端真正收到数据。~遥测报告依赖可用指标 URI、采样周期和后端实现。空报告需要检查定义与传感器有效性。|事件来源~订阅与筛选~目的端接收|在隔离网络建立事件接收端，记录请求时间与响应。~创建测试订阅，触发可控事件并核对 MessageId 与资源位置。~配置指标报告，对照原始传感器验证采样内容及取消后的行为。|事件和报告按定义到达，失败重试可观察，删除后不继续产生数据。~没有推送时查目的端 TLS、网络与过滤条件，SSE 断开时查会话和代理超时。|journalctl -b -u bmcweb --no-pager\nss -ntp\nbusctl list
redfish-oem-extensions|Redfish OEM 模式与后端|OEM 扩展需要稳定的命名空间和可描述的 schema。标准资源已有能力时，应优先保持标准语义。~路由处理器读取 D-Bus 后端并生成 JSON。异步回调中的对象生命周期、错误和权限必须明确。~验证包含 schema、URI、状态码与错误输入。单个 curl 成功无法证明接口契约完整。|OEM schema~路由处理器~后端接口|定义一个小型只读 OEM 资源，列明字段类型、单位与权限。~实现后端读取并验证对象缺失或服务重启时的响应。~用 Redfish Service Validator 和错误输入测试检查契约。|schema 与运行响应一致，后端失败返回可解释错误。~404 时查路由注册，schema 失败时查类型与名称空间，后端异常时查 D-Bus 回调。|systemctl status bmcweb\njournalctl -b -u bmcweb --no-pager\nbusctl list
mctp-pldm-guide|MCTP 传输与 PLDM 数据模型|MCTP 负责端点寻址与消息传输，PLDM 定义平台管理消息。Network、EID、TID 和传感器 ID 属于不同编号体系。~发现 endpoint 后，还需要查询 PLDM 类型与命令支持。传输可达并不保证设备支持监控或升级。~PDR 描述传感器与 effecter。平台发现、记录解析和 D-Bus 映射需要一起验证。|MCTP network~PLDM 消息~平台对象|记录物理绑定、network 与 EID，再验证 endpoint 可达性。~按原教程查询支持类型和 PDR，建立编号映射表。~对照一个传感器的协议值、D-Bus 值与资源归属。|端点编号和数据来源明确，重启或重新发现后映射仍正确。~超时先查传输与路由，数据缺失再查类型支持、PDR 和请求响应。|mctp link show\nmctp route show\nmctp neigh show\nsystemctl list-units '*pldm*'
spdm-guide|SPDM 认证与度量策略|SPDM 在 requester 与 responder 之间协商能力、算法并执行认证、度量或安全会话。协议支持范围取决于设备实现。~证书链证明身份可信，度量值支持判断固件状态。两者都需要预先配置的信任根或预期策略。~安全会话不自动证明固件符合策略。验收应分别检查身份、度量比较和会话建立。|能力协商~身份与度量~策略判断|记录设备支持版本、算法和证书槽位。~在实验端验证证书链和挑战响应，再查询度量值。~用已知预期值和不匹配场景检查策略、日志与资源状态。|身份验证与度量结论可独立解释，失败原因能够定位。~证书失败查信任根与时间，度量失败查基线版本，会话失败查协商算法与消息状态。|busctl list\nsystemctl list-units '*spdm*'\njournalctl -b --no-pager -n 80
firmware-update-guide|固件上传、验证与激活|固件更新包含上传、格式识别、签名验证、兼容性检查、写入和激活。每一步需要明确进度与失败状态。~上传完成与运行新版本是不同里程碑。ApplyTime、重启策略和双镜像优先级会影响生效时间。~恢复路径需要与 Flash 布局、U-Boot 和持久化数据设计配合。未经验证的镜像应先在可恢复实验板测试。|镜像验证~Flash 写入~启动与健康检查|保存当前版本、镜像校验值、布局和恢复方式。~在实验平台更新匹配 machine 的镜像，持续观察任务与软件对象状态。~重启后核对实际运行版本及核心服务，再验证失败恢复流程。|新版本真实运行，持久配置符合预期，失败时可以恢复到已知版本。~激活失败查签名、machine 和空间，启动失败查分区、DTB 与串口日志。|busctl tree xyz.openbmc_project.Software.BMC.Updater\ncat /proc/mtd\ncat /etc/os-release\njournalctl -b --no-pager -n 80
intel-asd-acd-guide|Intel 调试通道与崩溃采集|ASD 提供调试访问，ACD 面向自动崩溃数据采集。调试通道和故障采集的权限及使用场景不同。~PECI、JTAG 和平台错误信号支撑不同数据来源。CPU 型号与固件版本会影响可采集字段。~原教程中的错误注入属于实验室验证内容。验收应优先确认采集链路、触发来源和数据完整性。|故障信号~采集服务~诊断文件|确认平台支持的采集服务与接口，记录 CPU 型号和配置。~使用平台提供的受控采集入口收集样本，核对完成状态和文件大小。~对照日志解释关键字段，测试存储配额和保留策略。|采集成功或失败均有明确状态，文件可关联到故障时间和平台版本。~缺字段时查 CPU 能力和电源状态，采集超时查 PECI、触发顺序和资源限制。|systemctl list-units '*crashdump*'\nsystemctl list-units '*asd*'\ndf -h\njournalctl -b --no-pager -n 80
amd-debug-management-guide|AMD APML 与旁带监控|SB-TSI 提供温度接口，SB-RMI 提供管理及状态通道。APML 软件和内核驱动需要匹配处理器支持。~I2C 接线、地址和驱动绑定是基础条件。温度可读取不代表所有管理命令都可用。~故障采集与调试能力依赖厂商实现和平台权限。教程示例需要结合实际版本验证。|旁带总线~SB-TSI 与 SB-RMI~管理服务|核对器件地址和 CPU 支持，检查驱动绑定。~读取温度并与 D-Bus 发布值对照。~按平台文档查询管理能力和错误记录，保存版本及限制。|温度与管理数据来源明确，未知命令的错误可解释。~请求超时查供电和总线路径，温度异常查单位、驱动及 CPU 固件状态。|dmesg | grep -Ei 'sbrmi|sbtsi|apml'\nls /sys/bus/i2c/devices\ngrep . /sys/class/hwmon/hwmon*/name
logging-guide|Journal、事件日志与 SEL|Journal 记录进程运行信息，结构化事件日志表达管理事件，SEL 为 IPMI 提供事件记录。不同日志需要用时间和事件标识关联。~事件严重级别、MessageId 和附加数据影响解释。日志数量限制与轮转策略关系到长期可观测性。~删除日志会影响证据保留。实验中先导出样本，再测试轮转或清理策略。|服务日志~结构化事件~外部日志接口|记录一个可控事件的触发时间，分别查询 journal、D-Bus 和 SEL。~解释严重级别与附加数据，核对外部接口的事件显示。~在测试环境验证容量限制、重启持久化和导出流程。|同一事件在各接口中可关联，日志容量受控且关键证据可导出。~SEL 缺失时查 logger 与信号，journal 正常而事件缺失时查事件提交路径。|journalctl -b --no-pager -n 80\nipmitool sel list\nbusctl tree xyz.openbmc_project.Logging
sdr-guide|SDR 传感器记录与换算|SDR 描述传感器编号、实体、单位及换算参数。传感器值与记录定义共同决定客户端显示。~Full、Compact 和 FRU locator 等记录承担不同用途。错误的实体映射会造成设备归属混乱。~OpenBMC 的 SDR 可基于 D-Bus 与配置动态生成。重启或配置变化后应验证编号稳定性和客户端发现。|传感器对象~SDR 记录~IPMI 读数|读取 SDR 列表和一个完整记录，解释单位与实体字段。~比较 IPMI 数值与 D-Bus 真实读数及阈值。~重启后再次查询，记录传感器编号和记录变化。|IPMI 显示正确单位与范围，传感器归属及阈值一致。~换算异常时检查系数和指数，记录缺失时查对象接口及 SDR 生成条件。|ipmitool sdr list\nipmitool sdr elist\nipmitool sensor list
linux-debug-tools-guide|用户态与内核诊断工具|日志、GDB、strace 和 sanitizer 面向不同故障类型。先确定崩溃、阻塞、资源耗尽或数据竞争，再选择工具。~调试符号需要匹配二进制版本。ASan、UBSan、TSan 等工具有架构和资源条件，不能默认在所有 BMC 上启用。~调试配置会增加镜像与运行开销。实验镜像应记录配置，生产镜像另行确认资源和行为。|故障分类~工具证据~源码定位|保存崩溃日志、二进制版本与可复现步骤。~对一个测试服务使用日志或调用跟踪，定位失败系统调用。~在支持环境运行对应 sanitizer，将报告关联到具体源码。|诊断结论有原始证据和复现条件，修复后同一场景不再失败。~无法回溯查符号与版本，工具运行失败查架构支持、权限和内存。|journalctl -b -p err --no-pager\ncoredumpctl list\nps -eo pid,comm,rss\ncat /proc/meminfo
espi-guide|eSPI 通道与主机通信|eSPI 将主机与 BMC 的多类旁带通信组织为不同通道。Peripheral、Virtual Wire、OOB 和 Flash 通道的用途不同。~控制器驱动、设备树与主机固件配置需要匹配。接口节点出现后仍需验证通道握手和数据流。~平台迁移不能只复制寄存器地址或旧 LPC 配置。应核对 SoC 支持、内核分支和硬件连线。|控制器~通道协商~用户态消费者|检查设备树节点、pinmux 和内核配置。~从启动日志确认控制器与通道状态，再检查设备节点。~按平台测试方案验证目标通道，记录 Host 启动阶段与错误状态。|需要的通道正确启用，消费者能获取有效数据，错误可追踪。~通道不可用时查 BIOS、驱动和协商状态，无数据时查消费者与 Host 条件。|dmesg | grep -i espi\nls /dev/*espi*\ncat /proc/interrupts
unit-testing-guide|单元测试与依赖替身|单元测试验证函数、状态机和错误处理的契约。GTest 表达断言，GMock 隔离 D-Bus、文件和硬件等外部依赖。~测试应覆盖成功、边界和失败条件。只复制实现逻辑的测试难以发现真实行为错误。~异步回调与时间相关逻辑需要可控调度或替身。测试要避免依赖真实系统时钟和偶然执行顺序。|被测逻辑~依赖替身~行为断言|选择一个有明确输入输出的功能，写出预期契约。~覆盖有效输入、无效输入和后端失败，再检查错误传播。~在项目现有测试框架中运行并保存失败复现。|修改破坏契约时测试能失败，恢复实现后稳定通过。~偶发失败查共享状态、时间依赖和异步对象生命周期。|meson test -C build --print-errorlogs\nctest --test-dir build --output-on-failure
robot-framework-guide|Robot 系统测试与资源清理|系统测试从外部接口验证完整功能。Robot Framework 把测试步骤、变量、关键字和结果报告组织起来。~目标地址、凭证、平台能力和测试前置状态需要参数化。不能把某个平台的资源 ID 假定为所有板卡通用。~Setup 与 Teardown 需要处理失败后的恢复。测试改变电源、网络或账号时，应有明确清理逻辑。|测试参数~关键字执行~报告与恢复|先运行只读接口测试，验证目标与认证配置。~为一个功能写出前置条件、操作、预期与清理步骤。~检查 report 和 log，将失败归为环境、平台能力或行为回归。|测试可重复执行且不残留状态，失败报告包含足够证据。~大面积失败先查连接和前置条件，单个断言失败再查接口与实现。|robot --version\npython -m pip show robotframework\nls ./logs
linux-kernel-driver-development|内核驱动匹配与 probe|设备树 compatible 与驱动 of_match_table 共同决定匹配。驱动存在但 probe 未执行，常见原因是匹配或依赖问题。~hwmon、GPIO 和总线驱动应遵循相应子系统接口。资源申请、错误返回和移除路径影响可靠性。~内核补丁需要通过配置、配方和实际镜像保存。动态加载成功不能代替完整启动验证。|设备描述~驱动匹配~资源与 probe|确认 Kconfig、Makefile 与设备树匹配字符串。~观察 probe 日志、绑定路径和 deferred probe 列表。~验证正常读数及错误输入，保存内核版本和补丁。|驱动稳定绑定，错误路径可恢复，重启后保持正确行为。~未匹配查 compatible，延迟 probe 查时钟、供电和 GPIO 依赖。|dmesg | tail -n 80\ncat /sys/kernel/debug/devices_deferred\nls /sys/bus/i2c/drivers\nuname -r
secure-boot-image-signing|安全启动与镜像签名|安全启动逐级验证下一阶段代码，更新签名验证检查待安装镜像。两条路径相关但需要分别配置和验证。~信任根、签名私钥和验证公钥承担不同职责。密钥保存、吊销和轮换需要与制造及运维流程配合。~成功启动已签名镜像只覆盖正常路径。还应在可恢复实验条件下验证篡改、错误密钥与恢复行为。|硬件信任根~启动验证链~镜像更新验证|列出启动各阶段的验证者、被验证对象和公钥来源。~构建实验签名镜像并核对串口验证日志。~测试已知无效镜像的拒绝路径，保留板卡恢复方法和证据。|验证覆盖预期阶段，无效镜像被拒绝且失败状态明确。~失败时查签名范围、算法、DTB/FIT 内容和密钥部署。|openssl version\ncat /proc/mtd\ndmesg | grep -Ei 'secure|verified|signature'
multi-host-support|多主机实例与资源隔离|多个 Host 共享一个 BMC 时，状态、控制、串口和日志需要按实例区分。默认 host0 不能作为全部主机的代表。~systemd 模板、IPMB 总线和 GPIO 配置需要保持一致编号。共享 PSU 或风扇又需要明确公共资源归属。~并发操作会暴露错误的全局状态或硬编码路径。验收需要验证单独控制和同时运行。|Host 实例~独立资源~共享资源|整理 Host 编号、IPMB、GPIO 和控制台映射表。~逐个查询状态及资源，验证接口没有串到另一主机。~在实验平台并发操作并检查共享服务、事件和恢复逻辑。|每个 Host 状态独立，公共资源归属明确，故障不误影响另一 Host。~串线问题查实例参数、硬编码路径和总线地址。|systemctl list-units 'phosphor* @*'\nsystemctl list-units 'obmc*'\nbusctl list
performance-optimization|启动、内存与镜像性能|优化应从实际测量开始。启动关键路径、RSS、CPU 占用和镜像大小分别对应不同问题。~移除包、关闭功能和调整压缩会改变系统能力。每次优化应记录节省量以及功能验证范围。~缓存和启动并行并非越多越好。BMC 资源有限，额外后台任务可能扩大峰值内存或 I/O 竞争。|性能基线~定位瓶颈~对照验证|记录启动时间、空闲与负载内存以及主要进程占用。~选择一个明确瓶颈做小范围修改，保持测量条件一致。~比较前后数据并复测功能，关注峰值和长时间运行。|性能改善有可重复数字支持，管理功能和故障保护保持有效。~平均值改善但偶发超时增加时，检查峰值负载和资源竞争。|systemd-analyze\nsystemd-analyze critical-chain\nps -eo pid,comm,rss --sort=-rss\ndf -h
bios-firmware-management|BIOS 配置与固件管理|BIOS 固件升级与 BIOS 属性配置属于不同流程。属性可能需要主机重启后生效，待生效与当前值要明确区分。~PLDM、厂商工具或 Flash 访问提供不同更新路径。主机状态、总线 mux 与写保护影响是否能安全访问。~多 Host 平台需要明确每个 BIOS 的归属。更新和属性操作不能只依赖默认实例。|BIOS 属性~更新传输~生效与验证|查询 BIOS 资源与属性注册表，记录当前值和待生效值。~确认平台使用的升级路径、恢复方式与主机前置状态。~在实验机验证一个受支持属性的生效周期，再核对版本信息。|属性与固件版本能关联到正确 Host，操作后的生效状态明确。~更新失败查状态和 mux，属性无变化查 ApplyTime、支持范围和主机固件处理。|systemctl list-units '*bios*'\nbusctl list\ncat /proc/mtd
debug-dump-collection|诊断包采集、下载与配额|诊断包汇总日志、配置和运行信息，为复现困难的故障保留现场。采集内容应能关联到版本与时间。~采集可能消耗 CPU、内存和存储。并发数量、大小配额和保留策略直接影响 BMC 稳定性。~诊断包可能包含敏感信息。导出、访问权限和脱敏需要与实际运维流程结合。|采集请求~内容与配额~导出与保留|列出平台支持的 dump 类型和采集入口。~在测试目标生成一次诊断包，核对状态、时间与文件大小。~下载后确认可解包并检查关键日志，测试配额与失败清理。|诊断包可用且不耗尽空间，失败或取消后没有持续占用。~卡住时查采集脚本、权限与资源，下载失败查接口和文件存在状态。|systemctl list-units '*dump*'\ndf -h\nps -eo pid,comm,rss\njournalctl -b --no-pager -n 80
post-code-monitoring|POST 码采集与启动阶段|POST 码描述主机固件的启动阶段。含义依赖 BIOS 或平台定义，不能把一个码表套用到所有主机。~BMC 从 LPC、eSPI 或其他路径捕获代码，再由服务保存和暴露历史。采集路径和显示路径需要分别检查。~时间戳与启动轮次有助于定位停滞阶段。重复值可能是正常循环，也可能是卡住，需要结合主机日志。|主机输出~捕获驱动~历史与接口|确认主机固件启用 POST 输出，核对捕获路径。~记录一次完整启动的代码与时间序列。~结合 BIOS 文档解释阶段，检查重启后的轮次和历史保留。|代码序列连续且属于正确 Host，可定位实际停滞阶段。~无代码查捕获接口和主机配置，历史丢失查服务与存储策略。|systemctl list-units '*post*'\ndmesg | grep -Ei 'snoop|post|espi'\njournalctl -b --no-pager -n 60
pldm-platform-monitoring|PLDM Type 2、PDR 与 effecter|Type 2 定义平台监控与控制。PDR 描述传感器、effecter、单位、状态集合和实体关系。~numeric 与 state sensor 表达不同数据。读数还可能包含不可用状态，不能忽略状态字段只取数值。~effecter 是控制对象，写入前确认对应实体、能力和允许状态。PDR 解析错误会导致错误映射。|PDR 仓库~sensor 读数~effecter 控制|查询端点能力和 PDR，记录 TID、sensor ID 与实体编号。~读取一个数值与一个状态传感器，解释返回状态。~在实验设备验证受支持控制并确认反馈与事件更新。|协议对象映射正确，单位、状态和事件与实际设备一致。~读数错误查 PDR 单位与解析，无事件时查事件接收和订阅配置。|mctp route show\nsystemctl list-units '*pldm*'\njournalctl -b --no-pager -n 80
pldm-firmware-update|PLDM Type 5 升级状态机|PLDM 固件更新按协议状态机完成协商、组件选择、数据传输、验证与激活。每一步都有命令和返回状态。~设备描述符与组件匹配决定包是否适用。固件包格式正确仍可能不匹配目标设备。~传输由请求方与设备协同推进，超时和取消需要正确收尾。激活后应重新发现版本和能力。|包与设备匹配~组件传输~验证与激活|记录设备描述符、当前版本和支持的更新能力。~在可恢复实验设备上使用匹配固件包，采集状态迁移和进度。~完成后重新查询版本，验证失败、取消和重试的清理行为。|组件版本按预期更新，状态机无残留，失败原因明确。~匹配失败查描述符，传输卡住查请求顺序、块大小和超时。|mctp neigh show\nsystemctl list-units '*pldm*'\njournalctl -b --no-pager -n 80
dice-security|DICE 身份派生与度量链|DICE 根据设备秘密与软件度量派生后续身份材料。软件变化会影响派生身份和证明链。~证明方生成证据，验证方依据信任与预期度量做判断。仅有证书链不足以决定所有软件状态可接受。~DICE、Secure Boot 和 SPDM 可以配合，但各自承担不同任务。集成方式取决于硬件信任根及当前实现。|设备秘密~软件度量~派生身份与证明|列出平台是否具备 DICE 支持及秘密保护机制。~追踪一个启动阶段的度量和身份材料来源。~在测试设计中定义更新前后的允许度量，检查验证方策略。|证据能关联到设备和软件版本，更新策略允许合法变化并拒绝不符合基线的状态。~验证失败查证书链、度量基线和派生上下文，不能仅比较证书文件名称。|dmesg | grep -Ei 'dice|caliptra|tpm'\nopenssl version\nbusctl list
sgpio-serial-gpio|SGPIO 时钟、位序与 GPIO 映射|SGPIO 通过串行移位扩展输入输出。物理位序、时钟和链路长度决定数据对应关系。~ASPEED 的 GPIO 软件编号规则与输入输出映射需要按驱动核对。ngpios 的含义不能直接照搬到其他 SoC。~Nuvoton 的 SIOX 与 ASPEED SGPIO 存在实现差异。设备树 compatible、属性和驱动支持应分别确认。|串行链路~输入输出位序~GPIO line|核对 CPLD 或移位器件链路、时钟和位序。~检查控制器 probe，再将 gpioinfo 中的 line 对应到硬件信号。~验证输入和输出及边沿行为，长链路时记录频率与稳定性。|每一 line 对应正确物理位，输入输出互不混淆。~固定值查时钟和位序，输出无效查编号、方向和消费者。|gpioinfo\ndmesg | grep -Ei 'sgpio|siox'\ncat /proc/interrupts
device-firmware-update|CPLD、VR 与设备升级集成|不同设备有不同写入协议、版本提供者和工厂实现。统一软件接口不能消除底层器件差异。~升级可能临时切换 mux、绑定驱动或获取总线控制权。失败路径需要保证资源和路由恢复。~原教程中的 TPM 管理能力不等于支持 TPM 固件升级。设备类型和当前实现的能力需要逐项核实。|设备发现~写入实现~版本与资源恢复|记录设备类型、更新方式和实际支持的组件匹配。~在实验设备验证发现与固件库存，再核对更新前置状态。~完成或失败后检查 mux、驱动绑定和版本读回，确认其他设备仍正常。|更新能力描述准确，资源恢复完整，版本来源可信。~库存缺失查配置与版本提供者，立即失败查器件匹配和总线所有权。|busctl list\nls /sys/bus/i2c/devices\nsystemctl list-units '*firmware*'\njournalctl -b --no-pager -n 80
porting-reference|板级移植整体路线|移植从硬件资料和启动链路开始，逐步完成 layer、machine、设备树、内核与用户态配置。~先建立串口和恢复能力，再验证基本网络、传感器及电源控制。复杂接口建立在这些基础能力之上。~同一 SoC 的参考板只能提供起点。地址、GPIO、Flash 和时序必须依据实际原理图。|硬件映射~启动与驱动~管理功能验收|建立硬件清单、总线图、GPIO 表与 Flash 布局。~用最小镜像验证串口、内存、Flash 和网络。~逐项接入传感器、电源与接口，每项保存证据和未完成问题。|移植清单中每项都有可重复验证步骤和明确通过条件。~先定位失败层级，避免同时修改 bootloader、内核和用户态而失去可追踪性。|cat /proc/device-tree/model\ncat /proc/mtd\ndmesg | tail -n 80\nsystemctl --failed
machine-layer-guide|平台 layer 与 machine 配置|layer.conf 定义配方搜索及兼容性，machine.conf 选择平台硬件与功能。应用配方和配置包要进入最终镜像。~bbappend 通过名称与版本模式匹配原配方。layer 优先级不代表所有变量都按直觉覆盖。~平台配置应放到自有 layer，并明确与当前 Yocto 系列及上游配方的关系。|layer 元数据~machine 选择~镜像内容|创建或检查平台 layer，核对 BBFILES 与兼容性。~通过工具确认 layer 已加入构建且 bbappend 命中目标配方。~检查 machine 的设备树、U-Boot 和配置包，再生成镜像验证。|最终展开的变量和安装内容与平台预期一致。~Nothing PROVIDES 时查依赖和配方，append 无效时查命名与版本匹配。|bitbake-layers show-layers\nbitbake-layers show-appends\nbitbake -e obmc-phosphor-image
device-tree-guide|设备树、pinmux 与板级连线|设备树描述硬件实例与资源。SoC dtsi 提供控制器基础节点，板级 dts 选择启用、引脚和外部器件。~compatible、reg、interrupts、clocks 和 GPIO 属性需要符合 binding。编译通过不能证明接线正确。~构建使用的 DTB 与运行中的设备树必须核对。修改错误文件会造成看似配置无效。|SoC 描述~板级覆盖~运行 DTB|从原理图建立控制器、地址、引脚和极性清单。~选择一个简单器件添加节点并核对 binding，构建对应 DTB。~启动后检查运行树和驱动绑定，再验证实际功能。|运行设备树匹配板卡，驱动与硬件资源正确绑定。~probe 缺失查 compatible 和 status，GPIO 错位查 chip、offset 与 pinmux。|cat /proc/device-tree/model\nls /sys/firmware/devicetree/base\ndmesg | tail -n 80
u-boot-guide|U-Boot 启动、环境与恢复|U-Boot 初始化硬件并按环境与配置加载内核、DTB 和文件系统。内存、Flash 与启动参数决定后续行为。~环境变量的保存位置、大小和冗余机制要与 Flash 布局一致。错误环境可能改变镜像选择或启动地址。~A/B 选择、启动计数和健康检查共同实现回退。仅存在两个镜像并不代表恢复链路已完成。|硬件初始化~镜像选择~内核启动|通过串口记录 U-Boot 版本、启动参数和 Flash 检测。~在实验板核对镜像与 DTB 加载地址，保存环境备份。~验证正常启动和可恢复的失败场景，检查回退条件。|启动来源与参数明确，失败时能通过已验证方式恢复。~环境损坏查位置和 CRC，内核不启动查镜像格式、DTB 与加载地址。|version\nprintenv\nhelp\nbdinfo
verification-guide|功能验收与证据记录|验收应覆盖启动、电源、传感器、散热、网络和管理接口。每项需要前置条件、操作与可观察结果。~正常路径之外还应覆盖服务重启、传感器失效和配置持久化。测试范围应与平台能力相符。~日志、截图、配置版本和原始读数构成验收证据。只有口头描述难以支持后续回归。|测试条件~可观察结果~证据归档|建立功能矩阵并标记 QEMU 或真板所需条件。~逐项记录测试步骤、响应、日志和实际硬件结果。~对失败写出层级定位和复测条件，再运行自动回归。|验收报告可复现且明确未覆盖项，功能结论有证据支持。~接口成功但硬件无动作时继续核对反馈，偶发失败需记录时序和负载。|systemctl --failed\nobmcutil state\nipmitool sensor list\njournalctl -b -p err --no-pager
arm-platform-guide|ARM 平台角色与启动组件|Host CPU 的架构与 BMC SoC 的架构需要分开描述。ARM 服务器仍可能使用 ASPEED 管理控制器。~某些 ARM 启动方案包含 TF-A 和 U-Boot，但实际组件由目标 SoC 及 BSP 决定。不要把一种参考流程套用到所有平台。~meta-arm 提供相关配方和工具，machine 仍需选择正确 tune、设备树与启动配置。|Host 架构~BMC SoC~BSP 启动链|先列出 Host 与 BMC 的独立架构和芯片型号。~核对参考 BSP、启动阶段与 layer 依赖。~检查实际 ELF 架构和启动日志，验证通信协议与平台服务。|架构选择与实际硬件一致，启动组件和管理能力都有明确来源。~ABI 错误查 tune 与依赖，启动失败查 BSP 支持和各阶段加载关系。|uname -m\nfile /bin/busybox\ncat /proc/device-tree/model\nbitbake-layers show-layers
entity-manager-advanced|复杂 Probe 与 FRU 动态配置|复杂 Probe 可以组合多个发现条件。条件越多越需要保留原始输入和逐项匹配证据。~FRU 字段可用于名称、编号和配置替换。字段缺失、格式变化或重复记录会影响创建对象。~静态 Inventory 与动态 Entity Manager 的职责不同。迁移时应避免重复对象和冲突的关联。|FRU 发现~复合条件~配置生成|读取原始 FRU 和发现接口，记录用于匹配的字段。~逐项验证 AND、OR 或正则条件，再检查生成对象。~测试字段缺失和重复记录，比较迁移前后库存与关联关系。|复杂匹配可解释，对象命名稳定且没有重复库存。~配置消失查 Probe 输入，替换错误查字段格式、模板变量和索引。|journalctl -b -u entity-manager --no-pager\nbusctl tree xyz.openbmc_project.EntityManager\nipmitool fru print
flash-layout-optimization-guide|Flash 分区、压缩与双镜像|Flash 布局约束 bootloader、内核、只读文件系统和持久化区域。偏移量、大小和单位必须统一。~静态 MTD 与 UBI 的镜像构造和运行管理不同。选择取决于介质、容量、更新和磨损需求。~A/B 布局需要计算两套镜像、共享数据和环境空间。镜像压缩节省空间，也会改变启动与更新成本。|分区容量~镜像构造~更新与回退|根据真实 Flash 容量计算分区起止地址，检查重叠与对齐。~比较构建产物大小与运行 MTD 或 UBI 布局。~逐项裁剪或调整压缩，重测启动、更新和持久数据。|所有组件满足容量约束，回退和持久化数据路径完整。~超限查组件大小，挂载失败查类型与布局，回退循环查健康标记和启动计数。|cat /proc/mtd\ndf -h\nls -lh tmp/deploy/images\nmount
ast2700-enablement|AST2700 架构与 BSP 验证|原教程介绍 AST2700 的 64 位迁移和新外设。驱动可用性随 BSP 与内核分支变化，应以实际源码和硬件验证为准。~32 位到 64 位迁移影响指针、数据布局、格式化输出和依赖库。不能只修改编译 tune。~Caliptra、I3C、LTPI 等能力需要硬件、固件、驱动及用户态配套。设备节点出现不代表整条功能链完成。|64 位 ABI~新外设驱动~信任根集成|固定 BSP 和内核版本，建立所需外设支持清单。~检查程序架构与关键数据结构，再运行单元和接口回归。~逐项验证外设 probe、通信和错误处理，记录尚未支持部分。|支持范围有版本依据，迁移后功能和资源稳定性通过验证。~启动失败查设备树与 BSP，段错误查 ABI 和指针转换，外设缺失查 binding 与驱动。|uname -m\nuname -r\nfile /bin/busybox\ndmesg | tail -n 80
jenkins-ci-cd-infrastructure|仓库 CI 与整机回归|仓库级 CI 验证代码格式、编译和单元测试，系统级 CI 验证镜像构建、QEMU 启动与接口。~容器、缓存和种子构建减少环境差异与重复工作。缓存加速不能代替测试结果。~Gerrit 状态与 Jenkins 日志关联评审。定位失败需要找到具体阶段和原始任务日志。|代码评审~仓库测试~系统验证|阅读一个 CI 结果并列出格式、编译、单元和系统测试阶段。~在本地用对应容器复现一个失败。~核对测试产物、源码版本和平台覆盖，区分环境失败与代码回归。|提交结论可追溯到具体日志，系统测试覆盖实际目标能力。~所有任务同时失败先查环境，单个平台失败再查 machine 配置和平台差异。|git rev-parse HEAD\ngit status --short\nls .github\nbitbake-layers show-layers
ami-onetree-vs-openbmc|上游 OpenBMC 与商业发行方案|原教程比较上游 OpenBMC 与 AMI OneTree 的开发方式。商业方案的具体能力取决于合同、版本和供应商资料。~比较应关注源码可得性、平台支持、开发工具、验证范围和维护责任。不能用品牌名称推断所有功能。~选择方案时结合项目硬件、交付周期和长期更新要求，逐项核对需要维护的定制内容。|开发流程~平台支持~维护责任|列出项目必须支持的硬件和接口。~对照上游源码与供应商实际交付资料，标记可验证功能。~整理补丁来源、升级路径和责任边界，形成可复核比较表。|比较结论由当前版本资料支持，未知项明确保留。~遇到能力描述差异时先核对版本和授权范围，不把教程概览当作供应商承诺。|git remote -v\ngit rev-parse HEAD\nbitbake-layers show-layers
yocto-bitbake-build-optimization|下载缓存、sstate 与构建调优|DL_DIR 保存下载源，SSTATE_DIR 保存任务结果。共享下载减少网络开销，sstate 复用还取决于任务签名与兼容性。~BB_NUMBER_THREADS 与 PARALLEL_MAKE 控制不同并行层级。CPU 数量之外还要考虑内存和磁盘 I/O。~rm_work、hash equivalence、uninative 与镜像裁剪承担不同优化任务。每项都应通过时间和空间数据验证收益。|下载复用~任务结果复用~并行资源|记录冷构建与热构建时间、峰值内存和磁盘占用。~配置稳定缓存目录，检查日志中的 sstate 命中与任务执行。~逐项调整并行度或构建范围，比较相同输入下的结果。|优化结果可重复，缓存权限和输入版本明确。~缓存不命中查签名，OOM 查双层并行，磁盘增长查工作目录和缓存保留。|bitbake -e obmc-phosphor-image\nfree -h\ndf -h\ndu -sh downloads sstate-cache tmp
contributing|教程与示例维护|技术文档需要同时维护说明、代码、依赖与验证步骤。版本变化可能让旧示例的接口或选项失效。~示例应说明前置条件、目标环境、预期输出和限制。可复制命令仍需替换平台参数。~贡献教程时应保留来源和许可证，修正内容与实际验证记录一起提交。|问题记录~示例修正~复核与评审|选择一段教程示例，对照当前版本源码核对路径与参数。~在指定环境复现并记录成功或失败条件。~整理最小修正与验证证据，检查链接和代码块格式。|读者能按明确环境重复操作，文档说明与代码一致。~示例失效时先查版本差异，再判断教程缺漏或实现变化。|git diff --check\ngit status --short\ngit log -1 --oneline
`.trim().split('\n'));
export const curriculum=rows.map(row=>{const a=row.split('|');return {id:a[0],title:a[1],concept:a[2].split('~'),flow:a[3].split('~'),lab:a[4].split('~'),result:a[5].split('~'),commands:a.slice(6).join('|').split('\\n').join('\n')};});
