# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ceb-gnrd"
BBFILE_PATTERN_meta-ceb-gnrd = "^${LAYERDIR}/"

LAYERSERIES_COMPAT_meta-ceb-gnrd = "wrynose whinlatter"
